global.monster[0]= 0;
global.monster[1]= 0;
global.monster[2]= 0;
global.monster[3]= 0;
global.turn= 0;
switch(global.battlegroup) {
    case 256:
        global.monstertype[0]= 1;
        global.monstertype[1]= 1;
        global.monstertype[2]= 1;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 2;
        global.battlelv= 1;
        global.actfirst= 0;
        global.extraintro= 0;
        global.monsterinstance[0]= instance_create(216, 136, 205/* obj_testmonster */);
        global.monsterinstance[1]= instance_create(418, 136, 205/* obj_testmonster */);
        global.monsterinstance[2]= instance_create(14, 136, 205/* obj_testmonster */);
        break;
    case 255:
        global.monstertype[0]= 2;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/prebattle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= global.battlegroup + 3000;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.monsterinstance[0]= instance_create(216, 136, 199/* obj_dummymonster */);
        break;
    case 140:
        global.monstertype[0]= 3;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/prebattle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= global.battlegroup + 3000;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.monsterinstance[0]= instance_create(216, 136, 203/* obj_fakefroggit */);
        break;
    case 135:
        global.monstertype[0]= 4;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= global.battlegroup + 3000;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.monsterinstance[0]= instance_create(216, 136, 213/* obj_froggit */);
        break;
    case 134:
        global.monstertype[0]= 5;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= global.battlegroup + 3000;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.monsterinstance[0]= instance_create(214, 16, 206/* obj_whimsun */);
        break;
    case 133:
        global.monstertype[0]= 4;
        global.monstertype[1]= 5;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= global.battlegroup + 3000;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.monsterinstance[0]= instance_create(216, 136, 213/* obj_froggit */);
        global.monsterinstance[1]= instance_create(317, 16, 206/* obj_whimsun */);
        break;
    case 132:
        global.monstertype[0]= 6;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= global.battlegroup + 3000;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.monsterinstance[0]= instance_create(216, 156, 212/* obj_moldsmal */);
        break;
    case 131:
        global.monstertype[0]= 6;
        global.monstertype[1]= 6;
        global.monstertype[2]= 6;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= global.battlegroup + 3000;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msc= 0;
        global.msg[0]= "* You tripped into a&  line of Moldsmals.";
        global.monsterinstance[0]= instance_create(15, 156, 212/* obj_moldsmal */);
        global.monsterinstance[1]= instance_create(217, 156, 212/* obj_moldsmal */);
        global.monsterinstance[2]= instance_create(421, 156, 212/* obj_moldsmal */);
        break;
    case 130:
        global.monstertype[0]= 4;
        global.monstertype[1]= 4;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* A pair of Froggits hop&  towards you.";
        global.monsterinstance[0]= instance_create(116, 136, 213/* obj_froggit */);
        global.monsterinstance[1]= instance_create(320, 136, 213/* obj_froggit */);
        break;
    case 129:
        global.monstertype[0]= 6;
        global.monstertype[1]= 6;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Moldsmal and Moldsmal&  block the way.";
        global.monsterinstance[0]= instance_create(116, 156, 212/* obj_moldsmal */);
        global.monsterinstance[1]= instance_create(320, 156, 212/* obj_moldsmal */);
        break;
    case 128:
        global.monstertype[0]= 6;
        global.monstertype[1]= 7;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Migosp crawled up close!";
        global.monsterinstance[0]= instance_create(116, 156, 212/* obj_moldsmal */);
        global.monsterinstance[1]= instance_create(320, 136, 207/* obj_migosp */);
        break;
    case 127:
        global.monstertype[0]= 7;
        global.monstertype[1]= 8;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Vegetoid came out of the earth!";
        global.monsterinstance[0]= instance_create(116, 136, 207/* obj_migosp */);
        global.monsterinstance[1]= instance_create(320, 136, 208/* obj_vegetoid */);
        break;
    case 126:
        global.monstertype[0]= 9;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Loox drew near!";
        global.monsterinstance[0]= instance_create(218, 124, 209/* obj_loox */);
        break;
    case 125:
        global.monstertype[0]= 9;
        global.monstertype[1]= 8;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Vegetoid and Loox attacked!";
        global.monsterinstance[0]= instance_create(116, 124, 209/* obj_loox */);
        global.monsterinstance[1]= instance_create(320, 136, 208/* obj_vegetoid */);
        break;
    case 124:
        global.monstertype[0]= 9;
        global.monstertype[1]= 8;
        global.monstertype[2]= 7;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Loox and co. decided to&  pick on you!";
        global.monsterinstance[0]= instance_create(14, 124, 209/* obj_loox */);
        global.monsterinstance[1]= instance_create(218, 136, 208/* obj_vegetoid */);
        global.monsterinstance[2]= instance_create(422, 136, 207/* obj_migosp */);
        break;
    case 123:
        global.monstertype[0]= 8;
        global.monstertype[1]= 8;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* A pair of Vegetoids&  came out of the ground!";
        global.monsterinstance[0]= instance_create(116, 136, 208/* obj_vegetoid */);
        global.monsterinstance[1]= instance_create(320, 136, 208/* obj_vegetoid */);
        break;
    case 122:
        global.monstertype[0]= 9;
        global.monstertype[1]= 9;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* A pair of Loox&  decided to pick on you!";
        global.monsterinstance[0]= instance_create(116, 124, 209/* obj_loox */);
        global.monsterinstance[1]= instance_create(320, 124, 209/* obj_loox */);
        break;
    case 121:
        global.monstertype[0]= 8;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Vegetoid came out of the earth!";
        global.monsterinstance[0]= instance_create(218, 136, 208/* obj_vegetoid */);
        break;
    case 120:
        global.monstertype[0]= 0;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.3, 0.5);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 2;
        global.msg[2]= "* But nobody came./%";
        break;
    case 101:
        global.monstertype[0]= 11;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/ghostbattle.ogg");
        caster_loop(global.batmusic, 1, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Here comes Napstablook.";
        if(global.flag[6] == 1)
            global.msg[0]= "* Here comes Napstablook^1.&* Same as usual.";
        global.monsterinstance[0]= instance_create(266, 106, 210/* obj_napstablook */);
        break;
    case 100:
        global.monstertype[0]= 9;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Loox drew near!";
        global.monsterinstance[0]= instance_create(218, 124, 209/* obj_loox */);
        break;
    case 95:
        global.monstertype[0]= 10;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/boss1.ogg");
        caster_loop(global.batmusic, 1, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Toriel blocks the way!";
        global.monsterinstance[0]= instance_create(250, 42, 211/* obj_torielboss */);
        break;
    case 94:
        global.monstertype[0]= 13;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Doggo blocks the way!";
        global.monsterinstance[0]= instance_create(196, 28, 247/* obj_movedoge */);
        break;
    case 93:
        global.monstertype[0]= 14;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Lesser Dog appears.";
        global.monsterinstance[0]= instance_create(216, 38, 220/* obj_lesserdoge */);
        break;
    case 92:
        global.monstertype[0]= 15;
        global.monstertype[1]= 16;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Dogi assault you!";
        global.monsterinstance[0]= instance_create(208, 38, 245/* obj_mandog */);
        global.monsterinstance[1]= instance_create(208, 38, 246/* obj_womandog */);
        break;
    case 91:
        global.monstertype[0]= 17;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/dogsong.ogg");
        caster_loop(global.batmusic, 0.7, 0.95);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* It\'s the Greater Dog.";
        global.monsterinstance[0]= instance_create(208, 38, 224/* obj_greatdog */);
        break;
    case 90:
        global.monstertype[0]= 25;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        if(global.flag[67] < 0)
            global.batmusic= caster_load("music/papyrusboss.ogg");
        else  global.batmusic= caster_load("music/papyrus.ogg");
        if(scr_murderlv() < 7) {
            if(global.flag[67] < 0) caster_loop(global.batmusic, 0.9, 1);
            else  caster_loop(global.batmusic, 0.5, 1);
        } else  caster_loop(global.batmusic, 0, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Papyrus blocks the way!";
        if(scr_murderlv() >= 7) global.msg[0]= "* Papyrus is sparing you.";
        global.monsterinstance[0]= instance_create(250, 42, 232/* obj_papyrusboss */);
        break;
    case 89:
        global.monstertype[0]= 22;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Gyftrot confronts you!";
        global.monsterinstance[0]= instance_create(208, 38, 235/* obj_gyftrot */);
        break;
    case 88:
        global.monstertype[0]= 18;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        if(global.flag[57] == 2) {
            global.msg[0]= "* Chilldrake saunters up!";
            global.monsterinstance[0]= instance_create(216, 38, 253/* obj_chilldrake */);
        } else  {
            global.msg[0]= "* Snowdrake flutters forth!";
            global.monsterinstance[0]= instance_create(216, 38, 252/* obj_snowdrake */);
        }
        break;
    case 87:
        global.monstertype[0]= 18;
        global.monstertype[1]= 18;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Chilldrakes flutter forth!";
        global.monsterinstance[0]= instance_create(114, 38, 253/* obj_chilldrake */);
        global.monsterinstance[1]= instance_create(318, 38, 253/* obj_chilldrake */);
        break;
    case 86:
        global.monstertype[0]= 19;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Icecap struts into view.";
        global.monsterinstance[0]= instance_create(216, 38, 216/* obj_icecap */);
        break;
    case 85:
        global.monstertype[0]= 19;
        global.monstertype[1]= 18;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        if(global.flag[57] == 2) {
            global.msg[0]= "* Icecap and Chilldrake&  pose like bad guys.";
            global.monsterinstance[0]= instance_create(114, 38, 216/* obj_icecap */);
            global.monsterinstance[1]= instance_create(318, 38, 253/* obj_chilldrake */);
        } else  {
            global.msg[0]= "* Icecap and Snowdrake&  pose like bad guys.";
            global.monsterinstance[0]= instance_create(114, 38, 216/* obj_icecap */);
            global.monsterinstance[1]= instance_create(318, 38, 252/* obj_snowdrake */);
        }
        break;
    case 84:
        global.monstertype[0]= 21;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Jerry clings to you!";
        global.monsterinstance[0]= instance_create(216, 127, 217/* obj_jerry */);
        break;
    case 83:
        global.monstertype[0]= 19;
        global.monstertype[1]= 21;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Icecap appears^1.&* Jerry came too.";
        global.monsterinstance[0]= instance_create(15, 38, 216/* obj_icecap */);
        global.monsterinstance[1]= instance_create(216, 127, 217/* obj_jerry */);
        break;
    case 82:
        global.monstertype[0]= 19;
        global.monstertype[1]= 21;
        global.monstertype[2]= 18;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Icecap and Snowdrake&  confront you^1, sighing.&* Jerry.";
        global.monsterinstance[0]= instance_create(15, 38, 216/* obj_icecap */);
        global.monsterinstance[1]= instance_create(216, 127, 217/* obj_jerry */);
        if(global.flag[57] == 2)
            global.monsterinstance[2]= instance_create(388, 38, 253/* obj_chilldrake */);
        else  global.monsterinstance[2]= instance_create(388, 38, 252/* obj_snowdrake */);
        break;
    case 81:
        global.monstertype[0]= 23;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Aaron flexes in!";
        global.monsterinstance[0]= instance_create(216, 38, 289/* obj_aaron */);
        break;
    case 80:
        global.monstertype[0]= 24;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Special enemy Temmie appears&  here to defeat you!!";
        global.monsterinstance[0]= instance_create(216, 38, 291/* obj_tembattle */);
        break;
    case 79:
        global.monstertype[0]= 12;
        global.monstertype[1]= 26;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* You walk into Moldsmal.";
        global.monsterinstance[0]= instance_create(114, 156, 212/* obj_moldsmal */);
        global.monsterinstance[1]= instance_create(316, 156, 293/* obj_moldsmalx */);
        break;
    case 78:
        global.monstertype[0]= 28;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Woshua shuffles up.";
        global.monsterinstance[0]= instance_create(114, 136, 256/* obj_woshua */);
        break;
    case 77:
        global.monstertype[0]= 29;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Shyren hides in the corner&  but somehow encounters you&  anyway.";
        global.monsterinstance[0]= instance_create(218, 36, 259/* obj_shyren */);
        break;
    case 76:
        global.monstertype[0]= 31;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/dummybattle.ogg");
        caster_loop(global.batmusic, 0.9, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Mad Dummy blocks the way!";
        global.monsterinstance[0]= instance_create(270, 80, 287/* obj_maddummy */);
        break;
    case 75:
        global.monstertype[0]= 23;
        global.monstertype[1]= 28;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* You shouldn\'t read this.";
        global.monsterinstance[0]= instance_create(114, 38, 289/* obj_aaron */);
        global.monsterinstance[1]= instance_create(318, 136, 256/* obj_woshua */);
        obj_woshbody.con= 1;
        obj_woshbody.alarm[4]= 80;
        break;
    case 74:
        global.monstertype[0]= 32;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/undyneboss.ogg");
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= " %%";
        global.monsterinstance[0]= instance_create(210, 20, 272/* obj_undyneboss */);
        break;
    case 73:
        global.monstertype[0]= 33;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/mettatonbattle.ogg");
        caster_loop(global.batmusic, 0.9, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Mettaton attacks!";
        global.monsterinstance[0]= instance_create(316, 190, 297/* obj_mettatonb_quiz */);
        instance_create(412, 126, 307/* obj_questionasker */);
        break;
    case 72:
        global.monstertype[0]= 34;
        global.monstertype[1]= 35;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Royal Guard attacks!";
        global.monsterinstance[0]= instance_create(18, 34, 309/* obj_bara01 */);
        global.monsterinstance[1]= instance_create(432, 34, 310/* obj_bara02 */);
        break;
    case 71:
        global.monstertype[0]= 36;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Tsunderplane gets in the way!&* Not on purpose or anything.";
        global.monsterinstance[0]= instance_create(46, 36, 327/* obj_tsunderplane */);
        break;
    case 70:
        global.monstertype[0]= 37;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Vulkin strolls in.";
        global.monsterinstance[0]= instance_create(106, 125, 337/* obj_vulkin */);
        break;
    case 69:
        global.monstertype[0]= 38;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Pyrope bounds towards you!";
        global.monsterinstance[0]= instance_create(108, 7, 343/* obj_pyrope */);
        break;
    case 68:
        global.monstertype[0]= 12;
        global.monstertype[1]= 12;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* You walk into Moldsmal.";
        global.monsterinstance[0]= instance_create(214, 156, 212/* obj_moldsmal */);
        global.monsterinstance[1]= instance_create(418, 156, 212/* obj_moldsmal */);
        break;
    case 67:
        global.monstertype[0]= 28;
        global.monstertype[1]= 23;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Woshua and Aaron appear.";
        global.monsterinstance[0]= instance_create(116, 136, 256/* obj_woshua */);
        global.monsterinstance[1]= instance_create(318, 38, 289/* obj_aaron */);
        break;
    case 66:
        global.monstertype[0]= 28;
        global.monstertype[1]= 26;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Moldbygg and Woshua appear.";
        global.monsterinstance[0]= instance_create(116, 136, 256/* obj_woshua */);
        global.monsterinstance[1]= instance_create(318, 156, 293/* obj_moldsmalx */);
        // obj_moldsmalx
        with(293) {
            with(mypart1) instance_destroy();
            visible= 0;
            stage= 1;
            global.monstername[myself]= "Moldbygg";
            mypart1= instance_create(x, y, part1);
            mypart1.stage= 1;
            global.hurtanim[myself]= 0;
            image_index= 0;
            scalevalue= 0.01;
        }
        break;
    case 65:
        global.monstertype[0]= 39;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/spider.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Muffet traps you!";
        global.monsterinstance[0]= instance_create(214, 37, 360/* obj_spiderb */);
        break;
    case 64:
        global.monstertype[0]= 40;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/mettatonbattle.ogg");
        caster_loop(global.batmusic, 0.9, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Mettaton attacks!";
        global.monsterinstance[0]= instance_create(316, 190, 298/* obj_mettatonb_second */);
        break;
    case 63:
        global.monstertype[0]= 41;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/undyneboss.ogg");
        caster_loop(global.batmusic, 0.9, 1.2);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= " %%";
        global.monsterinstance[0]= instance_create(250, 75, 275/* obj_undynebattle2 */);
        break;
    case 62:
        global.monstertype[0]= 42;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Madjick pops out of its hat!";
        global.monsterinstance[0]= instance_create(244, 50, 369/* obj_wizard */);
        break;
    case 61:
        global.monstertype[0]= 43;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Knight Knight blocks the way!";
        global.monsterinstance[0]= instance_create(56, 40, 378/* obj_finalknight */);
        break;
    case 60:
        global.monstertype[0]= 44;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Final Froggit was already there^1,&  waiting for you";
        global.monsterinstance[0]= instance_create(218, 110, 385/* obj_finalfroggit */);
        break;
    case 59:
        global.monstertype[0]= 45;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Astigmatism drew near.";
        global.monsterinstance[0]= instance_create(218, 110, 387/* obj_astigmatism */);
        break;
    case 58:
        global.monstertype[0]= 46;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Whimsalot rushed in!";
        global.monsterinstance[0]= instance_create(218, 110, 394/* obj_whimsalot */);
        break;
    case 57:
        global.monstertype[0]= 46;
        global.monstertype[1]= 44;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Whimsalot and Final Froggit&  appeared.";
        global.monsterinstance[0]= instance_create(106, 110, 394/* obj_whimsalot */);
        global.monsterinstance[1]= instance_create(416, 110, 385/* obj_finalfroggit */);
        break;
    case 56:
        global.monstertype[0]= 46;
        global.monstertype[1]= 45;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Whimsalot and Astigmatism&  appeared.";
        global.monsterinstance[0]= instance_create(106, 110, 394/* obj_whimsalot */);
        global.monsterinstance[1]= instance_create(416, 110, 387/* obj_astigmatism */);
        break;
    case 55:
        global.monstertype[0]= 44;
        global.monstertype[1]= 45;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Final Froggit and Astigmatism&  appeared.";
        global.monsterinstance[0]= instance_create(106, 110, 385/* obj_finalfroggit */);
        global.monsterinstance[1]= instance_create(416, 110, 387/* obj_astigmatism */);
        break;
    case 54:
        global.monstertype[0]= 44;
        global.monstertype[1]= 45;
        global.monstertype[2]= 46;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* What a nightmare!";
        global.monsterinstance[0]= instance_create(16, 110, 385/* obj_finalfroggit */);
        global.monsterinstance[1]= instance_create(218, 110, 387/* obj_astigmatism */);
        global.monsterinstance[2]= instance_create(420, 110, 394/* obj_whimsalot */);
        break;
    case 53:
        global.monstertype[0]= 43;
        global.monstertype[1]= 42;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Mercenaries emerge from&  the shadows.";
        global.monsterinstance[0]= instance_create(16, 50, 378/* obj_finalknight */);
        global.monsterinstance[1]= instance_create(366, 50, 369/* obj_wizard */);
        break;
    case 52:
        global.monstertype[0]= 47;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Defuse the bomb!";
        global.monsterinstance[0]= instance_create(256, 120, 401/* obj_battlebomb */);
        break;
    case 51:
        global.monstertype[0]= 47;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Defuse the dog!";
        global.monsterinstance[0]= instance_create(256, 180, 401/* obj_battlebomb */);
        global.monstername[0]= "Annoying Dog";
        global.monsterinstance[0].bombtype= 1;
        global.monsterinstance[0].mypart1.type= 1;
        global.monsterinstance[0].mypart1.bombtype= 1;
        global.monsterinstance[0].mypart1.sprite_index= 1519/* spr_tobdog_sleep_firebattle */;
        break;
    case 50:
        global.monstertype[0]= 47;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Defuse the extremely agile&  glass of water!";
        global.monsterinstance[0]= instance_create(256, 180, 401/* obj_battlebomb */);
        global.monstername[0]= "Extremely Agile Glass&     Of Water";
        global.monsterinstance[0].bombtype= 2;
        global.monsterinstance[0].mypart1.type= 2;
        global.monsterinstance[0].mypart1.bombtype= 2;
        global.monsterinstance[0].mypart1.sprite_index= 490/* spr_waterglass_battle */;
        break;
    case 49:
        global.monstertype[0]= 47;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Defuse the script!";
        global.monsterinstance[0]= instance_create(256, 100, 401/* obj_battlebomb */);
        global.monstername[0]= "Script Bomb";
        global.monsterinstance[0].bombtype= 3;
        global.monsterinstance[0].mypart1.type= 3;
        global.monsterinstance[0].mypart1.bombtype= 3;
        break;
    case 48:
        global.monstertype[0]= 47;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Defuse the basketball!";
        global.monsterinstance[0]= instance_create(256, 80, 401/* obj_battlebomb */);
        global.monstername[0]= "Basket Bomb";
        global.monsterinstance[0].bombtype= 4;
        global.monsterinstance[0].mypart1.type= 4;
        global.monsterinstance[0].mypart1.bombtype= 4;
        break;
    case 47:
        global.monstertype[0]= 47;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Defuse the present!";
        global.monsterinstance[0]= instance_create(250, 100, 401/* obj_battlebomb */);
        global.monstername[0]= "Present Bomb";
        global.monsterinstance[0].bombtype= 5;
        global.monsterinstance[0].mypart1.type= 5;
        global.monsterinstance[0].mypart1.bombtype= 5;
        break;
    case 46:
        global.monstertype[0]= 47;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Defuse the game!";
        global.monsterinstance[0]= instance_create(256, 100, 401/* obj_battlebomb */);
        global.monstername[0]= "Game Bomb";
        global.monsterinstance[0].bombtype= 6;
        global.monsterinstance[0].mypart1.type= 6;
        global.monsterinstance[0].mypart1.bombtype= 6;
        break;
    case 45:
        global.monstertype[0]= 49;
        global.monstertype[1]= 48;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Royal Guard attacks!";
        global.monsterinstance[0]= instance_create(46, 66, 312/* obj_bara04 */);
        global.monsterinstance[1]= instance_create(460, 66, 311/* obj_bara03 */);
        break;
    case 44:
        global.monstertype[0]= 36;
        global.monstertype[1]= 37;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Tsunderplane attacks!&* Not because it\'s jealous Vulkin&  is paying attention to you!";
        global.monsterinstance[0]= instance_create(46, 36, 327/* obj_tsunderplane */);
        global.monsterinstance[1]= instance_create(306, 125, 337/* obj_vulkin */);
        break;
    case 43:
        global.monstertype[0]= 38;
        global.monstertype[1]= 38;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* The rare and threatening&  Double Davis.";
        global.monsterinstance[0]= instance_create(106, 10, 343/* obj_pyrope */);
        global.monsterinstance[1]= instance_create(306, 10, 343/* obj_pyrope */);
        break;
    case 42:
        global.monstertype[0]= 37;
        global.monstertype[1]= 37;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* A strange parade blocks the&  path.";
        global.monsterinstance[0]= instance_create(106, 125, 337/* obj_vulkin */);
        global.monsterinstance[1]= instance_create(306, 125, 337/* obj_vulkin */);
        break;
    case 41:
        global.monstertype[0]= 50;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/mettatonbattle.ogg");
        caster_loop(global.batmusic, 0.9, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Mettaton attacks!";
        global.monsterinstance[0]= instance_create(300, 190, 299/* obj_mettatonb_third */);
        break;
    case 40:
        global.monstertype[0]= 51;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/mettaton_ex.ogg");
        caster_loop(global.batmusic, 1, 0.97);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Mettaton EX makes his premiere!";
        global.monsterinstance[0]= instance_create(210, 60, 403/* obj_mettatonex */);
        break;
    case 36:
        global.monstertype[0]= 53;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/amalgam.ogg");
        caster_loop(global.batmusic, 0.8, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Smells like sweet lemons.";
        global.monsterinstance[0]= instance_create(280, 20, 528/* obj_lemonbread */);
        break;
    case 35:
        global.monstertype[0]= 54;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/amalgam.ogg");
        caster_loop(global.batmusic, 0.8, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* ,";
        global.monsterinstance[0]= instance_create(240, 20, 550/* obj_reaperbird */);
        break;
    case 34:
        global.monstertype[0]= 55;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/snowy.ogg");
        caster_loop(global.batmusic, 0.9, 0.5);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* It\'s so cold.";
        global.monsterinstance[0]= instance_create(240, 20, 552/* obj_snowdrakemom */);
        break;
    case 33:
        global.monstertype[0]= 56;
        global.monstertype[1]= 56;
        global.monstertype[2]= 56;
        global.batmusic= caster_load("music/amalgam.ogg");
        caster_loop(global.batmusic, 0.8, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "*        drew near!";
        global.monsterinstance[0]= instance_create(15, 146, 554/* obj_memoryhead */);
        global.monsterinstance[1]= instance_create(217, 146, 554/* obj_memoryhead */);
        global.monsterinstance[2]= instance_create(421, 146, 554/* obj_memoryhead */);
        break;
    case 32:
        global.monstertype[0]= 57;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/sfx_woofenstein_loop.ogg");
        caster_loop(global.batmusic, 0.8, 0.85);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* It\'s the Amalgamate.";
        global.monsterinstance[0]= instance_create(180, 90, 555/* obj_endogeny */);
        break;
    case 31:
        global.monstertype[0]= 58;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        if(!caster_is_playing(global.batmusic)) {
            if(global.flag[501] == 0) global.batmusic= caster_load("music/xpart.ogg");
            else  global.batmusic= caster_load("music/xpart_2.ogg");
            caster_loop(global.batmusic, 0.8, 0.95);
        }
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* The Lost Soul appeared.";
        global.monsterinstance[0]= instance_create(296, 70, 558/* obj_ripoff_undyne */);
        break;
    case 30:
        global.monstertype[0]= 60;
        global.monstertype[1]= 61;
        global.monstertype[2]= 0;
        if(!caster_is_playing(global.batmusic)) {
            if(global.flag[501] == 0) global.batmusic= caster_load("music/xpart.ogg");
            else  global.batmusic= caster_load("music/xpart_2.ogg");
            caster_loop(global.batmusic, 0.8, 0.95);
        }
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* The Lost Souls appeared.";
        global.monsterinstance[0]= instance_create(76, 35, 559/* obj_ripoff_papyrus */);
        global.monsterinstance[1]= instance_create(456, 148, 560/* obj_ripoff_sans */);
        break;
    case 28:
        global.monstertype[0]= 59;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        if(!caster_is_playing(global.batmusic)) {
            if(global.flag[501] == 0) global.batmusic= caster_load("music/xpart.ogg");
            else  global.batmusic= caster_load("music/xpart_2.ogg");
            caster_loop(global.batmusic, 0.8, 0.95);
        }
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* The Lost Soul appeared.";
        global.monsterinstance[0]= instance_create(266, 100, 561/* obj_ripoff_alphys */);
        break;
    case 27:
        global.monstertype[0]= 62;
        global.monstertype[1]= 63;
        global.monstertype[2]= 0;
        if(!caster_is_playing(global.batmusic)) {
            if(global.flag[501] == 0) global.batmusic= caster_load("music/xpart.ogg");
            else  global.batmusic= caster_load("music/xpart_2.ogg");
            caster_loop(global.batmusic, 0.8, 0.95);
        }
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* The Lost Souls appeared.";
        global.monsterinstance[0]= instance_create(26, 94, 562/* obj_ripoff_toriel */);
        global.monsterinstance[1]= instance_create(356, 62, 563/* obj_ripoff_asgore */);
        break;
    case 26:
        global.monstertype[0]= 64;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/prebattle1.ogg");
        caster_loop(global.batmusic, 1, 0.25);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* In my way.";
        global.monsterinstance[0]= instance_create(260, 110, 284/* obj_mkid_battle */);
        break;
    case 25:
        global.monstertype[0]= 65;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/x_undyne.ogg");
        caster_loop(global.batmusic, 1, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* The heroine appears.";
        global.monsterinstance[0]= instance_create(210, 20, 282/* obj_undyne_ex */);
        break;
    case 24:
        global.monstertype[0]= 66;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/prebattle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.msg[0]= "* Glad Dummy lets you go.";
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.monsterinstance[0]= instance_create(216, 136, 286/* obj_gladdummy */);
        break;
    case 23:
        global.monstertype[0]= 67;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/mettaton_neo.ogg");
        caster_loop(global.batmusic, 0.7, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Mettaton NEO blocks the way!";
        global.monsterinstance[0]= instance_create(210, 0, 450/* obj_mettaton_neo */);
        break;
    case 22:
        // obj_battlebg
        with(185) instance_destroy();
        global.monstertype[0]= 68;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/zz_megalovania.ogg");
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "";
        global.monsterinstance[0]= instance_create(270, 110, 519/* obj_sansb */);
        break;
    case 21:
        global.monstertype[0]= 52;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "";
        global.monster[0]= 1;
        global.monsterinstance[0]= instance_create(116, 16, 482/* obj_asgore_finalintro */);
        global.mnfight= -999;
        break;
    case 20:
        global.monstertype[0]= 52;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/vsasgore.ogg");
        caster_loop(global.batmusic, 1, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* ASGORE attacks!";
        global.monsterinstance[0]= instance_create(208, 8, 478/* obj_asgoreb */);
        instance_create(0, 0, 483/* obj_purplegradienter */);
        instance_create(0, 0, 484/* obj_orangeparticlegen */);
        break;
    case 19:
        global.monstertype[0]= 70;
        global.monstertype[1]= 71;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* That doesn\'t seem correct.";
        global.monsterinstance[0]= instance_create(106, 110, 385/* obj_finalfroggit */);
        global.monsterinstance[1]= instance_create(416, 110, 387/* obj_astigmatism */);
        break;
    case 18:
        global.monstertype[0]= 70;
        global.monstertype[1]= 73;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Final Froggit stopped chasing&  Migospel around.";
        global.monsterinstance[0]= instance_create(106, 110, 385/* obj_finalfroggit */);
        global.monsterinstance[1]= instance_create(426, 130, 595/* obj_migospel */);
        break;
    case 17:
        global.monstertype[0]= 75;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Parsnik slithered out of the&  earth!";
        global.monsterinstance[0]= instance_create(111, 120, 597/* obj_parsnik */);
        break;
    case 16:
        global.monstertype[0]= 74;
        global.monstertype[1]= 74;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* You tripped over some&  Moldessas.";
        global.monsterinstance[0]= instance_create(118, 127, 600/* obj_moldessa */);
        global.monsterinstance[1]= instance_create(318, 127, 600/* obj_moldessa */);
        break;
    case 15:
        global.monstertype[0]= 74;
        global.monstertype[1]= 74;
        global.monstertype[2]= 74;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* A line of Moldessas block the&  path.";
        global.monsterinstance[0]= instance_create(18, 127, 600/* obj_moldessa */);
        global.monsterinstance[1]= instance_create(218, 127, 600/* obj_moldessa */);
        global.monsterinstance[2]= instance_create(418, 127, 600/* obj_moldessa */);
        break;
    case 14:
        global.monstertype[0]= 70;
        global.monstertype[1]= 72;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Can you believe it?";
        global.monsterinstance[0]= instance_create(106, 110, 385/* obj_finalfroggit */);
        global.monsterinstance[1]= instance_create(416, 120, 394/* obj_whimsalot */);
        break;
    case 13:
        global.monstertype[0]= 70;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Final Froggit hopped in...?";
        global.monsterinstance[0]= instance_create(208, 110, 385/* obj_finalfroggit */);
        break;
    case 12:
        global.monstertype[0]= 72;
        global.monstertype[1]= 75;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Whimsalot and Parsnik appeared.";
        global.monsterinstance[0]= instance_create(110, 120, 394/* obj_whimsalot */);
        global.monsterinstance[1]= instance_create(316, 120, 597/* obj_parsnik */);
        break;
    case 11:
        global.monstertype[0]= 74;
        global.monstertype[1]= 73;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Migospel flutters in^1, carrying&  Moldessa.";
        global.monsterinstance[0]= instance_create(116, 127, 600/* obj_moldessa */);
        global.monsterinstance[1]= instance_create(324, 130, 595/* obj_migospel */);
        break;
    case 10:
        global.monstertype[0]= 75;
        global.monstertype[1]= 73;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Migospel flutters in^1, carrying&  Parsnik.";
        global.monsterinstance[0]= instance_create(111, 120, 597/* obj_parsnik */);
        global.monsterinstance[1]= instance_create(324, 130, 595/* obj_migospel */);
        break;
    case 9:
        global.monstertype[0]= 75;
        global.monstertype[1]= 75;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Parsniks hissed out of the&  earth!";
        global.monsterinstance[0]= instance_create(111, 120, 597/* obj_parsnik */);
        global.monsterinstance[1]= instance_create(318, 120, 597/* obj_parsnik */);
        break;
    case 8:
        global.monstertype[0]= 75;
        global.monstertype[1]= 71;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Not only potatoes have eyes.";
        global.monsterinstance[0]= instance_create(111, 120, 597/* obj_parsnik */);
        global.monsterinstance[1]= instance_create(314, 110, 387/* obj_astigmatism */);
        break;
    case 7:
        global.monstertype[0]= 71;
        global.monstertype[1]= 71;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Eyes appeared from the shadows.";
        global.monsterinstance[0]= instance_create(108, 110, 387/* obj_astigmatism */);
        global.monsterinstance[1]= instance_create(312, 110, 387/* obj_astigmatism */);
        break;
    case 6:
        global.monstertype[0]= 71;
        global.monstertype[1]= 73;
        global.monstertype[2]= 74;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Looks like a real party.";
        global.monsterinstance[0]= instance_create(8, 110, 387/* obj_astigmatism */);
        global.monsterinstance[1]= instance_create(213, 130, 595/* obj_migospel */);
        global.monsterinstance[2]= instance_create(418, 127, 600/* obj_moldessa */);
        break;
    case 5:
        global.monstertype[0]= 71;
        global.monstertype[1]= 75;
        global.monstertype[2]= 74;
        global.batmusic= caster_load("music/battle2.ogg");
        caster_loop(global.batmusic, 0.75, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Party from Hell.";
        global.monsterinstance[0]= instance_create(18, 120, 394/* obj_whimsalot */);
        global.monsterinstance[1]= instance_create(218, 120, 597/* obj_parsnik */);
        global.monsterinstance[2]= instance_create(418, 127, 600/* obj_moldessa */);
        break;
    case 4:
        global.monstertype[0]= 76;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= caster_load("music/battle1.ogg");
        caster_loop(global.batmusic, 0.5, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* Glyde swooped in!";
        global.monsterinstance[0]= instance_create(188, 16, 228/* obj_glydeb */);
        break;
    case 3:
        global.monstertype[0]= 80;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.batmusic= 411;
        caster_loop(global.batmusic, 0.8, 1);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* You\'re blocked in politely!";
        global.monsterinstance[0]= instance_create(216, 78, 458/* obj_sosorry */);
        break;
    case 2:
        global.monstertype[0]= 99;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        caster_free(-3);
        global.batmusic= caster_load("music/xpart.ogg");
        caster_loop(global.batmusic, 0.8, 0.95);
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* It\'s the end.";
        global.monsterinstance[0]= instance_create(258, 8, 564/* obj_asrielb */);
        break;
    case 1:
        global.monstertype[0]= 100;
        global.monstertype[1]= 0;
        global.monstertype[2]= 0;
        global.flag[15]= 1;
        global.flag[500]= 1;
        if(!caster_is_playing(global.batmusic)) {
            if(global.flag[501] == 0) global.batmusic= caster_load("music/a2.ogg");
            else  global.batmusic= caster_load("music/xpart_2.ogg");
            caster_loop(global.batmusic, 0.8, 0.95);
        }
        global.msc= 0;
        global.battlelv= 0;
        global.actfirst= 0;
        global.extraintro= 0;
        global.msg[0]= "* ASRIEL blocks the way!";
        if(global.flag[501] == 2)
            global.msg[0]= "* ASRIEL\'s SOUL was awakened&  by the power of your&  friends!";
        if(global.flag[501] == 3) global.msg[0]= "* It\'s time to say goodbye.";
        global.border= 0;
        SCR_BORDERSETUP();
        global.monsterinstance[0]= instance_create(320, 48, 565/* obj_asrielfinal */);
        break;
}
