if(argument0 == 41)
    mydata= "yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}yf}p+l}k5g}f0\\0b}a0f0]}]/p/Y}\\.s/X}\\*W.k/W*X}\\*Z/c/[*X}\\*_.[/_*X}\\*W,]2d*X}\\*W/^*[)a*X}\\*W3a)b*X}\\*W6l*X}\\*W6j)V*X}\\*W6i)W*X}\\*W6l*X}\\*W6Z)f*X}\\*W6Y)b)Y*X}\\*W6l*X}\\*W6l*X}\\*W6e)[*X}\\*W6l*X}\\*W6l*X}\\*W6c)]*X}\\*W6b)^*X}\\*W6l*X}\\*W6a)_*X}\\*W6`)`*X}\\*W6j)V*X}\\*W6_)a*X}\\*W6^)b*X}\\*W6h)X*X}\\*Y4g)Y*X}],Y1\\)b,X}_-Y.g-Z}b,Z+d-]}Y/Y-e.`}Y0[-_-\\-X}[.W*Z-Y-Z2X}Z7Y0[2Z}_4Z*Z5[}e-b1_}yf}yf}~~~";
if(argument0 == 40)
    mydata= "yy_}yy_}yy_}yy_}yy_}yy_}yy_}yy_}yy_}yy_}yy_}yy_}yy_}yy_}yy_}yy_}p)o)p}o)q)o}n)s)n}n)s)n}m)u)m}m)u)m}m)u)m}m)l+[)m}l+Z+_0Y+l}j-Z-[3X-j}d4X,V+Z*V*V,W4d}[>W,V-Z+V,W=[}XBV+V7V+VAX}V<W1V9V0W<V}V*W4Z1V*Z-Z*V0Z4W*V}X*e-X,\\+\\,W-e*X}Z*a,W*W+X+X)X,W+W)W,a*Z}\\7Y)W*W.W)W.W*W)X7\\}n)W+V;V+V)n}j*W)W3V+V3W)X)i}i)V)V)W2W-W2W)V)V)h}h)W*X0V3V0X*W)g}h)\\.X3X.\\)g}g)]*V,V)V1V)V/])f}g)^)V,V)V1V)V.^)f}h)_)V+W1W.^)g}i)_-V1V.^)h}j)^-V+V)V+V-^)i}t.V*V)V*V,`)i}k/Y,V/V,Y1h}j)\\)V*V,V-V,V*V)^)g}c-V)_0Z0a-b}a0_?_0`}_2^A^2^}^3^A^3]}]3_A_3\\}]0l-l0\\}\\/W8V.V+V.V8W/[}\\BV.V)V.VB[}\\C\\)\\C[}\\?V+V5V+V?[}]7V-W+V5V+W-V7\\}]7V,V,V7V,V,V7\\}^7Z*X7X*Z7]}^6]=]6]}_4^=^4^}a/a=a/`}t=s}d)aCp}d)ZL-i}d)VL5e}d*]I]*c}c)aEa)b}b)dAd)a}b)e?e)a}a)g=g)`}a)h;h)`}a)i9i)`}a)i9i)`}a)j7j)`}a)j7j)`}a)k5k)`}b)j5j)a}b)k3k)a}c)j3j)b}d)j1j)c}e)i1i)d}f)h1h)e}g)g1g)f}h)e)^)e)g}g+d)^)d+f}e*f)`)f*d}d)g)b)g)c}c)f*d*f)b}b)`5\\5`)a}b)m*X*m)a}b)o)V)o)a}c+l)V)l+b}f-f)X)f-e}k9Z9j}yy_}yy_}yy_}yy_}~~~";
if(argument0 == 39)
    mydata= "yyW,yY}yx+Y+yV}yw)_)y}yv)a)x}yu)Z,Z)w}yt)Y0Y)v}yt)Z.Z)v}ys)Y)W,W)Y)u}ys)X+W*W+Y*s}yr)Y,Y,[*q}yq)Z-W-])p}yo*[,Y,[*q}ym*]+W*W+Y*s}yk*`)W,W)Y)u}yi*d.Z)v}yh)e0Y)v}r*l)h,Z)w}p*W)j)a+[*Z)x}n*W*j)`*X*Y*Y)y}l*W*k)`)\\*W*W*yV}j*W*l)`)_.yX}i)X*l)`)[7x}g*X*l)`)X,d+u}f)Y+k)`)X)k*s}e)Y+k)`)Z5`*q}d)Y,V)h)a)c/_*o}c)Y.V)f)a)b4^)n}b)Y.V)g)a)a)[0])m}a)Z-W)f)a)c,Z/\\)l}`)Z-W)g)a)f,Y.\\)k}_)Z-W*Y)a)b)b2Y-\\)j}^)Z.W*X)V)`)b)a)Z/X-[)j}])[-W,V)V)`)c)b,Y-X-[)i}\\)[-W.V)a)b)e-X,X-[)h}[)[.W-V)b)b)c1W,X-Z)h}[)[-W.V)a)c)b)Y.W,X,[)g}Z)[.W-V+`)c)c,X,W,W-Z)g}Z)[-W-W,V)])c)g+W+W,W,[)f}Y)[.W-V.V)\\)c)j*V+W+W-Z)f}Y)[-W-W-V)\\)e)k)V+W+W,Z)f}X)[.W-V-V)])e)l)V*W+W-Z)e}X)[-X,W-V)])e)l)V*X+W,Z)e}W)\\-W-V-V)^)e)l)V+W+W,Z)e}W)[.W,W-V)^)f)l)V*W+W,Z)e}W)[.W,W,V)_)f)l)V*W+W-Y)e}V)\\-X,W,V)^)h)k)V*W+W-Y)e}V)\\-W-V-V)^)h)k)V*W+W-Y)e}V)\\-W,W,V)_)i)j)V*W+W-Y)e}V)[.W,W,V)_)i)j)V*W+W-Y)e})\\.W,W,V)_)j)i)V*W+W-Y)e})\\.W,W,V)_)k)g)V+W+W-Y)e})\\.W,W,V)_)l)f)V+W+W,Z)e})\\.W,W,V)_)m)e)V*W,W,Z)e})\\.W,W,V)_)n)c)V+W,W,Z)e})\\.W,W,V)_)o)b)V+W+X,Y)f})\\.W,W,V)`)o*_)V+W,W-Y)f})\\.W-W,V)_)q*\\)V,W+X,Z)f})\\.X,W,V)_)s*Y)V,W,W-Z)f})\\.X,W,V)_)u,V,W,X-Y)g})\\.X-W,V)^)y,W-W-Z)g})\\/W-W,V)_)y*W-X-Z-c}V)\\.X-W,V)^)yZ+X,a+`}V)\\.X-W-V*\\)ys*^}V)\\/X-W-W*Z)ye/[)W)]}W)\\.X.W.W*Y)yc1Y,V)\\}W)\\/X.W/W+V)yb3X-V)[}W)\\/X/W0X*yb3Y-V)Z}X)\\/X/W2c,w1[-V)Y}X)\\0X/WDw/]-V)X}Y)\\/Y/XCx+`-V)W}Y)\\0Y0XAy)c)X)W}Z)\\0Y1Z<yV)c)Y)V}Z)\\1Y2^4yZ.V,\\)V}[)\\1Y4l+p-V.V,V+Y)}[)]1Z7d/i-V-V.V,V+V*V)}\\)]1[Lh-V-V.V,V+V*V)}\\)^1\\Jh-V-V.V,V+V*V)}])^2\\Hh-V-V.V,V+V*V)}^)^3^Cj,V-V.V,V+V*V)}_)^4`>k,V-V.V,V+V*V)}`)^6yf+V-V.V,V+V*V)}a)^8s+f+V-V.V,V+V)W)}b)_:m.f*V-V.V,V+V)V)V}c)`L3e*V-V.V,V+X)V}d)aL1f)V-V.V,V+X)V}e)bL/h-V.V,V+X)V}f)cL,i-V.V,V*X)W}g*dJm,V.V,[)W}i)fCr+V.V,Z)X}j*i:yV._)X}l*yye)Y}n+yya)Z}q*yy^)[}s+yyY*\\}v+t.w*^}y,l,[+q+`}yY.a-b,i,c}y_4k.^-g}yyc1l}yyy_}~~~";
if(argument0 == 38)
    mydata= "ya}ya}i1h}e)V5V)d}b,V5V,a}`-V7V-_}_.V7V.^}^.V9V.]}]/V+V1V+V/\\}\\/V*X1X*V/[}\\/X*V1V*X/[}[/V-V1V-V/Z}[.V.V1V.V.Z}Z/V/V/V*X*V/Y}Z.V0V/V)Z*V.Y}Y/V0V/V)Z*V/X}Y.V-V,V-V*Y,V.X}Y.V-V,V-V*Y,V.X}X/V-V-V+V*Y-V/W}X.V.W,V+V*X/V.W}X.V.X,V)V+W0V.W}X.V.X-V,V+V-V.W}W/V.Y0W+V-V/V}W/V.Z-V)V*V)V-V/V}W/V-\\+W)V*V)V-V/V}W/V,^*Y*V)V-V/V}W)V*V*V,^)Z*Y,V*V*V)V}W)V*V*V,^)Z*Y,V*V*V)V}W*W+V+_)Z*Y,V+W*V}W0V+]*W)W*Y+V0V}W0V,[*W*W)Y,V0V}W0V-Y)Y*\\,V0V}W0V-]+[-V0V}W1V,_*X.V1V}X0V,_*W/V0W}X0V-W*Y+W/V0W}X1V,V,W,W.V1W}X1V0Z+V.V1W}Y1V.\\0V1X}Y+V-V-]0V-V+X}Y+V*V+V-\\/V+V*V+X}Y+V*V,V,]-V,V*V+X}Z+W.V,\\,V.W+Y}Z4V,[+V4Y}[3V,Z,V3Z}[4V+V)W,V4Z}\\3V+V*V,V3[}]2V.W+V2\\}^1V*X)X*V1]}_0V)]*V0^}`.V+\\+V._}b+V.Y-V+a}e9d}c=b}_E^}]I\\}\\K[}]I\\}_E^}ya}ya}~~~";
if(argument0 == 37)
    mydata= "ye}g+t}g)V)V.m}g+V)X,k}j)V+V,\\+`}b+X+V)V)V,\\)V)`}b)V)X+V+V,Y+V)a}b+V)W+X-Y)V)W*_}a)X)^-Y+V+_}a,V+Z-Y)Y*`}V+V+[*V)V)Z-Y.Z+V+}V)V)V)V)V)Z)V+Y.Z+Z)V)V)V)V)}V+V+V*Y*\\.Z+Z)V+V+}Y)X+Y,Y.[,Y*\\}V-V,Y,W)V.V)Y,Y0V}W+W,X,W*V.V*X-Y+V*W}\\+Y,V)W.V+Y,Y+Z}\\+X-V*V.V)W+V-X+Z}[,V)V-V*V.W,W-V)W+Y}[,V)V.V)V.V,V/V*V+Y}[+V*V/W/V*V/V+V,X}Z,Z/W.V)V0Z,X}Z0W/W-W/W1X}Z2V,Z+])V2Y}[2Y,\\,X.]}`-W0X0W*`}^*Z>X+]}]-W
W,\\}]-VBV,\\}],VDV+\\}],V-Y;V+\\}^+V-Z1Y-V+\\}_*V.Z/Z-V*]}b.Z.Z.`}b.[-Z.`}c-[,[.`}c/Y,[-a}d/X,Y.b}d0W,X/b}d1W+W0b}d5W0c}d2V4c}d2V*V1c}d2V*V1c}d*W-V+V.W)c}e)X1V,X)c}e*X,Y-W*c}e*X+[+W+c}f*W+[+W*d}g*W*[*X)e}h)X)[)X*e}h*b)f}i*`*f}j)X)[*g}j*W)Z*h}k)W)Y*i}l+X*j}l,W*j}m+V*k}m.k}n,l}ye}ye}~~~";
if(argument0 == 36)
    mydata= "a/]/a}`)\\)[)\\)`}_)^)Y)^)_}_)^)Y)^)_}`,Z)Y)Z,`}d)X)[)X)d}d)X)[)X)d}d)X0X)d}d)X)[)X)d}d)c)d}c)e)c}b)g)b}a)[0[)a}a)X6X)a}`)X8X)`}`)W:W)`}V,]<],V}W-[,W0W,[-W}*W-X-W0W-X-W*},W,W-W0W-W,W,}.W*W-W0W-W*W.}0V)V.W0W.V)V0}V0W.W0W.W0V}V1V.W0W.V1V}W0V.W0W.V0W}X/V-Y.Y-V/X}Z-V+]*]+V-Z}\\+V*X)V)])V)X*V+\\}`*Y)_)Y*`}`*X)V)])V)X*`}`+\\,\\+`}`,Z.Z,`}`
`}`+W.W.W+`}`+X,Y,X+`}`+Y+Y+X,`}`,Y+W+Y,`}Z,W-Y.Y-W,Z}X/V-c-V/X}W.X.V*[*V.X.W}W,W*V-V,Y,V-V*W,W}V+W,V,V-Y-V,V,W+V}V*V.V,V-Y-V,V.V*V}V)V.W1[1W.V)V}W-Y0]0Y-W}a/V.V/a}a.V0V.a}b<b}d8d}y_}d)V)^)V)e}d)V)^)V)e}d)V)^)V)e}b*X*Z*X*c}`*\\)X)\\*a}_)^)X)^)`}_)^)X)^)`}`1Z1a}y_}~~~";
if(argument0 == 35)
    mydata= "yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yyr}yY2yd}yW2X,y_}y3W1y\\}x3Y2yZ}v4W*W*V-y[}u4W,Y)V*W*yX}t/X*X)X)W*Y,yW}s0V*_-W)y[}r0V)V)Y)W*W.y\\}q1V)W)X)V,W,`+s}q1V)X)X.V+a)V)s}p2V*X)V,X,W,Z)W)s}p1X+X)V3X*X)X)s}o2X)W*V)V+Z1V)W*t}o1Y)Z)V*W)V*W/X)V)t}o0Z)Z)Y*V*V)W+V)V*W)t}o)V.Z)W*V)W)V*V*V*Z)Z)t}o)V.Z+X)W)V*V*V*V*W)Z)t}q)V,[)Y*V)V*V*V*V*W)V*W)t}p*V,[)W)V*V)V*V*V*V*V*X)V)t}p)W)V*[)V)W*V)V*V*V*V*V*Y*t}v)[)V)X*W*V*V*V)W*V)W)u}n+a+X+V*V*V*V)V*W*V)u}n)W,]*Z+V)V*V*W+W,u}o*Y*[*Z,W*V*V+X+v}q)Z+X*[*V*X)V,Y*v}r)\\)W*\\*W*W,Z*v}l+Y)\\)W)]+W*V*[)w}i+X.[)a,W*y[}g*h)])Z,e9_}i.c)[*_)`,e-Z}o)c)W+W)_*w)Y}k.c+f/b.Y-Y}i*i+h+j,X)Z}g*l+f+o*\\}d+p+b+h-[)[}a+v)`*m.X)Z}d-p,_)p)W)X)Y}h.j)X+]*p)W)W)Y}j:[)[4p)W)V)Y}o/[.h3f)W)Z}u/Y)])W)^)^-b)V)Z}t)[-^)b+`*a)[}t)\\+_-`1Z+^)[}s)]+`*V*a)[*[*])Z}r)^+a)W)a)]*[*[)Z}p*_+a)]*Z)_+Z)Z)Z}o)b*W/X)[,Y*X)\\)V*Y*X)Z}o)V+[)W*V1W)Z.X)Z)[*W*X)Y)Y}o*V+Z)X)V)V0V)Y/X)Z)\\)Y)X)X)Y}s+V+Y+V1X1W*Z)\\)Z,X)Y}u,[?X)[)\\)\\+V*Y}q,W*[*X9V)V*[)\\*]*V)Y}q.^+V)V3V-V)\\)])]*V)Y}j+],\\?V)\\)]*])V)Y}h.^)^)Y5W+^)\\+\\+Y}g*V-V,b+W5V,^)\\+]*Y}g)Y2_,W3X+_)[,])Z}m3_*W3X+`)W-V)])Z}m4[)W*W1W.`-V)`)Z}m,V/b0X*V+e+e}m,W.^,W)W,V)V)V)V)`1d}n*X)W+^*V*V,V*V+V)V)`1^)Z}g+Y*[*V)]*V*W-W*Y)a0d}f.W*Z+\\*V*W)X+V)W)W)V)c*V)W)c}e*W,V*Y+X4Z)Z)Y)c*Y)])Z}e)Y/W+W2W)b+V)a/e}k-Y)W2Y*^*W+`2c}l-V*X-W*V)Z1Z+_2c}m0W+Z*V)\\*],_3b}m0V+Z)W)]+[,V)^*W)W,b}m1])W,Y)V*W*X*W)_)Z+c}m2[)[-Y*Y*Y)^)Z*d}n1[)^)V)X)V,[)^)Z*d}m-W+Z)^,V)V,^)])Y+d}m,V)W*Z)]*V-V+^)]*X+d}m,V*V*Y)])V,V*V+_)\\*X,c}m*V,V*Y)\\)W+X0\\)])W.b}l+V+W*Y)[*V*V)X)X*V*[)])W.b}l+V+V+X*[+V)V)X)X)V*])\\*V.b}l*W+V+X)\\)^)X)W)])[0V)b}l*W*V*Z)[*^)[)])Z3b}l)W+W)Y*[)_)[)])Z2c}l,V)W)Y*Z*_)[)V)\\)Y2c}l+W)W)Y)[)W/W*V+V)V)\\)Y1d}i-X)W)X*[)V*[*V)V*X+V)Y)X2d}d)X,V)[)X*\\*_)V0[)X2d}d)W-V)_)])`)Y-W*W)Y1d}c*V+V*V)_)[+`*Z+X)W)Y0e}c*V-W)_)Z*b*\\*W,Y0e}b1W)_/c*]*W*[/e}b-V)V)W)b*e*\\)V+]-V)e}a2W)b)e*_*^*V*V)e}`.V+X)b*d*_*^*V)W)e}`*V)W+f*d+_)`)V)h}_,W,f)])[+_*`)V)h}_+W-e)W)Y+])`*a)V)f}_*X-Y)_*Z+^)b)a)h}_*X*V)e)[+_)a*t}_+W-b-Z)]*V)Z)\\)t}[*X+V-a+V0X)[)X,\\*s}]5a1W+[*\\5o}[1W-W*Z0V.\\*]+V3V,g}X<Z7^.].W)Y1\\)Z}X0X2X3a1a-X1b}[9W8Y9^1j}y3X/Z
d}yyr}yyr}~~~";
if(argument0 == 34)
    mydata= "yyX,r,yx}yyW.p.yw}yyV-V*n*V-yv}yy-X)n)X-yu}yx-x-yt}yw-yV-ys}yw-yV-ys}yw-yV-ys}yw.x.ys}yw/v/ys}yx/t/yt}yx0c)c0yt}yy1a)a1yu}yy2_+_2yu}yr)\\2Z)X+X)Z2Z)yp}yr+[3X*W+W*X3Y+yp}yr)W+Y1W)W*V+V*W)W1W+W)yp}yr)Z+W/V*X,V,X*V2Z)yp}x)r*_-V)Z+X+Z)V.])r)v}x*r)`+V)\\/\\)V+^)r*v}x.n)a)V)l)V)_)n.v}y)W9`)b)l)`)`<w}y)Z<[)X)\\)n)^)[Bw}y)b9Y*\\)n)W)]DV*w}yV)c9W*\\)n)W*W*]<X)y}yV)f:[)p)V*V)\\>X*y}yV)h8[)p)W*[?Y*y}yW)i6Z)r)V*[=Z*yV}yX)j4Z)r)V*[;\\)yW}yX)k3Y)t*]8]*yW}yY)l2W)Y)l)Y)]5_+yW}yZ)l1V)Y)n)X*]0b*V)yW}y[)l0W,V)l)V,_,c+W)yW}y\\*k/[*l*X)o,X)yW}y\\)V*k,Y-l.m,V)X)yW}y\\)X*q,n,l,X)X)yW}y\\)Z)p,n.g-Z)X)yW}y\\)[,l+p+W+`/\\)X)yW}y\\)[)X,c+W+p-W+Y1_)X)yW}y\\)Z)]+_)W)X*p+W)W4c)W)yW}y\\)Z)`*\\)X)X*W)V)f)V)W+X)W0V)d)W)yW}y\\)Z)b)Z)Y)X*V)V)V)d)V)V)V+Y)_)d)W)yW}y\\)Y)c)Y)[)X,V)V)b)V)V-[)^)d)W)yW}y\\)Y)c)X)\\)X/V)V)\\)V)V0\\)])d)W)yW}y[)Z)c)W)^)X.W)V)Z)V)W/^)\\)d)X)yV}y[)Y)d)W)_)W.Z)X)Z._)\\)e)W)yV}y[)Y)d)f,\\)V)\\,a)[)e)W)yV}y[)Y)c*r)_)b)[)c)V)W)yV}y[)X)c+e-g)c)[)a-W)yV}y[)X)d-`+X,b*_*W)[)_0W)yV}y[)X)f,^/Y)^+b+\\)_0W)yV}yZ)X)j0V2W)Y+g+\\)_0X)y}yZ)X)p)W1V-Z)f*\\)`0X)y}yZ)X)o)W1\\)W)W)])[+\\)`0X)y}yZ)X)o)W1])W)W)]*X+])`0X)y}yZ)X*p4[)W*W)\\/X)Z)_1X)y}yY)Y.j)V1X.Y)W)[/X)[)_1Y)x}yY)Y2f)V1^)X)W)Z/X)\\)_1Y)x}yY)YDV1^)[)V1b)_1Y)x}yY)YDW3[)[)X-X0Z)^0Z)x}yY)ZDV0X.\\)X,W*])Y)^0Z)x}yY)ZDW/])[)X+X)`)X)^0Z)x}yY)ZEV.V)\\)Z)X)Z)b)W)_/Z)x}yX)\\
[,X/Z)^)c)X)^/[)w}yX)\\=`,Z)Y+_)d)W)^/[)w}yX)]9[)`-d)V)e)W)^/[)w}yX)_3`*o*W*e)W)^/[)w}yX)u)V+h*Y*V)e)X)]/[)w}yW)u)Z+g,W)f)X)^.\\)v}yW)t)`*a*[)f)Y)].\\)v}yW)s)u)V)f)Y)^,])v}yW)r)t*W)f)Z)],])v}yW)q)s,V)g)V)X)],])v}yV)q)q/V)g)V)Y)\\,^)u}yV)p)r/V)g)V)Y)\\,^)u}yV)o)s/V)W)d)V)Y)\\,^)u}yV)n)^)j/V)W)c)W*X)]+^)u}yV)m)]*k/V)W)c)V+X)]+^)u}y)n2`*_/V)W)c)V,m)t}y)v)c)^/V*V)c)V,W*]*_)t}x)u+d)]/W)V)c)\\4`)s}u+u,d*\\.X+b)\\6`+p}q,w.c)V)[.Y*b)\\8a,l}l-yW.c)V)[.V)X)b)\\9d-g}h,y\\-d)W)Z-W)Y)`)];g,c}a/y`-d)W)Z-V)Z)`)\\=j/\\}^+yg-d)X)Y,W)Z)_)])X7W+n+Y}[+yi.d)X)Y+W)[)_)\\)Y/X)X*Y,m+V}[)yk/c)Y)X*W)\\)_)\\)Z-Z*X+Z)n)V}[+yd*W0b)W*W)W)W)W+W)d+V)Z,]+X*X)l*W}^,yW1X-V,a)\\)X)]*Y1Z)Y-`)Y)W)i+Y}b+l4a.V-]*^)V)]:X)X)Y*_)Y+X:\\}e?m.V+V1a)^;W)X)[,[)Y)s}yr,V+V)t;W+`.V,t}yyy.V-V,yk}yyy.V-V,yk}yyyV-V-V+yl}yyyyyX}yyyyyX}~~~";
if(argument0 == 33)
    mydata= "yyy}y*u*y}y,q,y}y-o-y}y.Y8Y.y}m0Z-V>V-Z0m}l3X,V
V,X3l}l5V+VBV+V5l}l5V*V?V,V*V5l}l3W*V3]-W,V*W3l}m0W+V2W0W*V)V-V+W0m}m/V-V0W4W+V,V-V/m}n.V,V0V/W2V-V,V.n}q+V,V/V/V*V1V-V,V+q}p-V*W.V0V*V0V.W*V-p}o.V)W.V+X+V*V+X*V/W)V.o}p.X.V+V*V*V*V*V*V+V.X.p}q-X-V,V+V*W*V+V,V-X-q}r+X.V,V+V.V+V,V.X+r}x-V.Y.Y.V-x}x-V*X8X*V-x}x,V+Z4Z+V,x}w-V+W*W2W*W+V-w}w-V+V,V2V,V+V-w}v.V+V,W0W,V+V.v}v.V+W*X0X*W+V.v}v.V,[0[,V.v}v*V+V-Z0Z-V+V*v}w)V+V/X0X/V+V)w}y,VBV,y}yV+V1V.V1V+yV}yW+V0]0V+yW}yY*V0W*W0V*yY}y[)V/W*W/V)y[}y\\)W.V*V.W)y\\}ya4ya}yc0yc}yd.yd}a3q.q3a}b/X)V*n,n*V)X/b}b/W+V*m,m*V+W/b}b/W+W*l,l*W+W/b}b/X)W+m*m+W)X/b}c-V+Y*g+X*X+g*Y+V-c}e)_+e-W*W-e+_)e}d+_*d)V*Y*Y*V)d*_+d}q+c)W)V*V*V*V)W)c+q}\\*i*c)W)V+W+V)W)c*i*\\}\\*i+c)V*V*V+V*V)c+i*\\}s*d+]+d*s}^-[*]+b+W+V*W+b+]*[-^}]+V*V)V*V*^+c)V,V+V)c+^*V*V)V*V+]}\\)V*X*V+V*^+_*W-V,W*_+^*V+V*X*V)\\}[*X-V+W)_+]+V-V.V+]+_)W+V-X*[}^0V+V*_+[+V.V/V+[+_*V+V0^}[3[*_+X,V/V0V,X+_*[3[}W*W3\\*_/X/W/X/_*\\3W*W}V)V*W1V)\\*_,[-V)V.[,_*\\)V1W*V)V}Y,V.V*]*^*Z)X,V)V-W*Z*^*]*V.V,Y}Z+W,V*_*])Z*Y*V+V*Z*Z)]*_*V,W+Z}c*a*a*W+W-W+X*a*a*c}a*d*_*X7Y*_*d*a}s+\\*X9Y*\\+s}t,Y*Y-W+W-Z*Y,t}v,V*X)V,V*V)V*V,V)Y*V,v}w-X)V.W+W.V)Y-w}x+X*V;V+X+x}y)Y)V=V*Y)y}yY*V,V3V,W*yY}yW,V,W1W,W*yY}yW+W,W1W,W+yX}yV+W-W1W-W+yW}yV+W*V+W*X*W+V*W+yW}yV*X*W*W+V+W*W*Y*yV}y+X*X*V*X*V*X*Y+y}y+Y)Y)W)X)W)Y)Z+y}x+Z*Y)V)X)V)Y*[*y}x*\\+V-V-V+\\*y}x*_,V)V)V,_*y}w+_*V)Z)V*_+x}w*`)X)X)X)a*w}w*c*X*d*w}w*c*X*d*w}v+c*X*d*w}v*e*V*e*w}v*e*V*e*w}v*e*V*e*w}v*e*V*f*v}v+d*V*e+v}v,c*V*d,v}w,b*V*c,w}v+V)b*V*b)V+w}w)V)c*V*e)x}x)V)b*V*b+y}yc*X*yd}yc*X*yd}yc*X*yd}yc*X*yd}yb+X+yc}yb+X+yc}ya*V)X)V*yb}y`+\\+ya}y_+^+y`}yyy}yyy}~~~";
if(argument0 == 32)
    mydata= "ya}X*yW*X}W*yY*W}V+yY+V}V+yY+V}V+e0e+V}V,a6a,V}V-^:^-V}W.Y
Y.W}WL0W}XL.X}XL.X}Y9[9Y}Z8[8Z}\\6[6\\}]5[5]}]-Y-Y-Y-]}V)Z/X-Y-X/Z)V}V*X0X-Y-X0X*V}V5Y-W-Y5V}W5X-W-X5W}X4X-W-W5X}Y4W+[+W4Y}[3c3[}[1g1[}[/W*c*W/[}[.V+e+V.[}[-V+g+V-[}\\,V+g+V,\\}\\-V*g*V-\\}\\-V*g*V-\\}]-V*e*V-]}].V)e)V.]}^.V)c)V.^}^/e/^}_0a0_}])W2[2W)]}\\+W
W+\\}\\+X>X+\\}\\+Y<Y+\\}[,[8[+\\}[,^2^,[}[,Y)g)Y,[}Z+V)Y+c+Y,[}Z+V)Y0Y0Y)V+Z}Z*W)Y/[/Y)V+Z}Z*].[.]*Z}Z)^.[.^)Z}d-]-d}d-]-d}e,],e}e,],e}e,],e}f*_*f}f*_*f}g)_)g}g)_)g}ya}~~~";
if(argument0 == 31)
    mydata= "yk}p)Y)n}h+Y+W+Y+f}g-Y.Y-e}f/Y,Y/d}e,W+Y*Z*W,c}e,X*Y*Y+X+c}e+Y*V0V+X+c}l7i}W)i7g)V}V)i8g)V}V)h:f)V}W,c+X/X+c,V}W*V*b*d+_+V+V}W*W-]*a)Y*],W*W}X*Y,[*Y)\\+W*[,Y*W}Y*Y-Y*W+]*W*X-Z*X}Y+V.Z*W*Y)X)Y*Y1Z}[+V*\\*Y)X)]*\\*V*[}h*\\+\\*g}i)\\,[)h}j)[,Z)i}r)V)o}yk}g,c)V+f}e*Z*^+Y*d}c*[)W,V/[)c}b)\\)Y+V,X)[)b}b)[)Z)\\,\\)a}b)Y*V+W+V0\\)Y.W}c,W1V)W-])Z,W}i1V)W.\\)Z,W}i1V1\\)Z,W}e)W2V2V)Z)X)X)W}f4V3[)W)Y)W}g)V*V.W/V)\\)V)]}j)V*V)Y*V)V*]*_}l)k*_}y`)_}n)[)[)Z)a}n)[)[)Y)b}n)[)[,d}n)[)[,d}l+[*Z,d}k+\\,X.b}i-],j}i+`+j}yk}~~~";
if(argument0 == 30)
    mydata= "yc}n)m}m+l}l-k}i)W-W)h}i*V-V*h}i3h}a)\\3[)a}`*X)X3W)X*`}`*X*Y/X*X*`}_,V+c+V,_}_1a1_}^2a2^}^+Z+_,Y+^}]+\\+],[+]}]*],[,]*]}]*^,Y,^*]}]*^,Y,^*]}]*^-W-^*]}X)Y*Y.V+W+V.Y*Y)X}X)Y*W0X,X0W*Y)X}X*X5W,W5X*X}X+XHX+X}XL0X}X7V-W-V7X}Y2V+V,Y,V+V2Y}V)W2k2W)V}V*W/n0W*V}W2W)V*V)_)V*V)V3W}W3V)V*V+[+V*V)V3W}XL0X}YL.Y}ZL,Z}\\L\\}^H^}c>c}yc}yc}Z)yX)Y}[*x*Z}[,Y+f+Y,Z}\\4b4[}]6\\6\\}_G^}b3X3a}\\)X1V*Z*V1X)[}]3X*X*X3\\}^2X/X2]}`E_}_4\\4^}_2`2^}_0d0^}_/Z)Z)Z/^}_/X-V-X/^}_.[)Z)[.^}`-[)Z)[-_}`-h-_}a-V)Y)X)Y)V-`}Z+Z.Z)V)Z.Z+Y}[4\\)\\4Z}\\2f2[}^-l-]}yc}yc}~~~";
if(argument0 == 29)
    mydata= "yyyX}o)yya}o*yy`}o+yy_}m)V+c)s)y}m)V+`,s-u}k/V)\\.a.a.t}k2Z,c+X*c,s}i6X+c*V+W*c+s}h6Y+b,Y,b+s}k2Z+`8`+s}k-V/W,],V2V,],s}g1V0V8W0W8s}h-V)W,[5V)X.X)V5t}k*W*V)V)\\2X)X.X)W3u}k*V)W)W,f)X*W*X)y^}k)W)W)V,f*a*y]}f.V)V*W*h+_,y\\}g0W)V*\\1W,_,W1u}k,V-[)_.X*X._)V/l}k,V-Z,\\0W*W0\\,V*Y,h}k2f0V*V0d)\\+e}i6V._8_/V)^)d}i6V1]6]3V)^*b}l0X4\\4\\5V)`)a}l0V7\\2\\7V)`)`}n,X8\\0\\8V)a)_}n,X9\\.\\9W)Z0^}i)Z*Y:]*]:W)W+\\*]}h)[*Y;e;W)V)a)\\}g)Y0W;c;X*j}f)Z0Y9c:b-^}e)],]8a8b+X)_}d)^,_6a6b*Z)`}c)_,V)_5_5b*[)a}b1Z*V*`4]4b*])a}a)\\)W,g3V)W)V3n)a}`)\\)W1^+Y3W3X+j)a}_)\\)W3[*^1W1]*i)`}_)\\)V4Z)b/W/a)h)`}^)\\)W._)e-W-d)g)`}^)\\)W3Y)h*Y*g)f)`}])\\)W4Y)y^)f)`}])\\)W4X)i*X*i)f)_}])\\)W.^)h)\\)h)f)_}])\\)W3Y)g)^)g)f)_}])\\)W3Y)e*X-X*e)f)_}])\\)X,`*a*X1X*u)_}\\)^)W1]4Y3Y,W+V*Z)c)_}\\)^)X0X)i*V-V*^+V+[,`)^}[)\\-c,a)W*W-W*W*X+V+W*\\*^)Y)Y}[)[)`*\\*W+V*V+V*V*V/V*V-V+V+V+V)\\*\\)X*Y}Z)[)a+^,V*V+V*W3W-V+V+V+V*]*Z)W)V)Y}Y)[)b+[.V+V+V*W3W-W*V+V+V*_)Z*W)Y}X)Y+c+\\,V,V*V+X+X+Y,^*V+`-Y)Y}V/f+a+V+V+X*Z*Y+V)`*i)Z}n+`,V+V*Y*Z*Y*V)w)Z}n+`,V+V*h)w)[}n+_,V,V*f)V)e)f)[}n+_+W+V+g)g)d)\\}n+_)Y+V+g)g)d)\\}n+d*W+g)g)c)]}n+^)Y+V+X)`)X)g)b)^}n+^)Y*W+X)`)X)f)V)`)_}n+])Z)W,W*X)X)X*W)f)V)V+Z*`}n+])]+X+W*V*W+W)e)W)Y-b}n+\\)]+Y+V+V+V+V*d)X)k}n+\\)e5W)d)Y)k}n+[)h1Y)c)Z)k}n+[)f)`)W)a*[)k}n+[)g*\\*X)^+\\)l}n+[)h1Y)V0_)l}n,Y)k-[*f)m}m-Y)v)g)m}m-Y)u*f)n}m-Y)t*g)n}m-Y)s*g)o}m-Y)k)p)o}m-X)l)_)d)p}m-X)l)_)d)p}m-X)l)_)c)q}m-X)l)_)c)q}m-X)k)`)b)r}m-X)k)`)b)r}m-X)k+^)a)s}m-X)k)V*])a)s}m-X*i)V)V)])`)t}m-X)V)h)V)V)\\)a)t}m-X*V*e)V)V)])`)u}m-X)V)W*b)V)W)])],u}m.W)W*V+^*V)W)^)Z+y}l/X)X)X1W)W)_)X*X/r}l/X)Y+^*W)`)W)W+\\)q}j1Y)[1X)`)W)V*`)p}j3W)f)a)V)V)c)o}j3X)d)b)V)V)d)n}j3Y)`+c)V)V)e)m}yV*[+f*W)f)l}yX.n*e)k}yy-_*k}yyZ2m}~~~";
if(argument0 == 28)
    mydata= "yy}n/yY}l*\\*yW}k)`)yV}k)a)y}j)c)x}j)Y,\\)w}j)X)Y)\\)v}j)X)W)W)\\)u}k)X*V)W)[)u}l*X)X)\\)t}n+Z)[)t}v)\\)s}v)\\)s}v)])g.Z}k)^)^)^)\\)[)Y}j)V)])^)])V)Z)V)[)X}j)W)[)`)[)W)Y)W)\\)W}j)X.b.X)Y)X*V)V)V)W}Y.a)r)Z)Z)V)V*W}X)[)`)r)Z)Y)Z)W}W)V)[)`)p)[)Z)Y)W}V)W)\\)`)n)])X)Y)X}V)X*V)V)V)a*j*_)X)W)Y}V)Z)V)V*c+e*b.Z}V)Y)Z)f,^+o}V)Z)Y)a)]1r}W)X)Y)b,y\\}X)X)W)c.yZ}Y.d,V-],Y)i}n,W<j}n+V)Y8k}o)Y*[1m}o+W+V*V)v}p+W*V*V)V)V)V)p}q+Y*V)V)V)r}r-yW}t3s}k.c.m}i*[*_*[*k}h)_)])_)j}g)a)[)a)i}g)X,[)Y)[,X)i}g)W)Y)[)W)[)Y)W)i}g)V)[)W*V)W)V*W)[)V)i}g)V)\\)V*W*W*V)\\)V)i}h*\\)V*W*W*V)\\*j}i*\\)Y*Y)\\*k}r)Y*Y)t}s)X)Y)u}t)W)X)v}s)X)Y)u}s)X*Y)t}r)Z)X)u}s)Y)Y)t}r)Z)Z)s}r)Z)Z)s}q)a)s}j)Z)c)Z)l}j)X*e*X)l}j,i,l}k)m)m}^*V)\\*V+h*V*]*V)_}])X)[*V)X;W*V)[*W*^}`)\\)X*j*W*[*W)^}])W)\\)Z)h)e)^}])^*[)f)[)_)^}`*Y*])c*])Z)X)^}]*X)V+[)V)e*\\+W)X*^}d)])h+]*Y)_}^)b)k*b)_}_*^*m)V)^*`}`*X)X)q*X)X*a}a+V)W)s)X-b}d*V)u)W)f}f*v)V)f}e*x*f}yf)g}yy}~~~";
if(argument0 == 27)
    mydata= "yyyY}yZ)])yn}yZ)])yn}yZ)])yn}yZ*W*X)yn}o)c*W*W*c)y_}p)b*W*W*b)y`}p*a*W*W*a*y`}q*`*W*W*`*ya}q+_*W*W*_+ya}q,^+V*V+^,ya}q.\\+V*V+\\.ya}r0X,V*V,X0yb}r1V.\\)V1yZ)\\}r)V.W/[)W.V)yZ*[}t.W)V-[)W.y\\,Y}t.W)W,^.y]+Y}t*W*W)X+^*W*y\\-X}t*X)W)Y,X)X)X*y],X}t)Y)W*Y*Y)X)Y)y\\.W}yX+])yf.W}f)j+])V)j)r/V}f)j,[)W)j)r/V}e*j,[)W)j*q/V}e)V)i-Y)X)i)V)p0V}d)W)i-Y)X)i)W)n1V}d)W)i.W)Y)i)W)o/W}d)X)h.W)Y)h)X)n1V}d)X)h.W)Y)h)X)n0W}c)Z)g.W)Y)g)Z)l0X}c)Z)h-W)Y)g)Z)k1X}c)[)g-W)X)g)[)l/Y}c)\\)a*X-W)X)X*a)\\)k0Y}c)])^*Z-W)X)Z*^)])j1Y}d)]*[)],W)X)\\)[*])k0Z}b+^/^,W)W)Y+W/^,g0[}b+])])\\,W)W)\\)])],f1[}a)X)[)W/],W)W)],Z)[)Y)e0\\}`)Z)Z)V)e+W)W)f)Z)[)c1\\}_)\\)X)h+W)V)h)X)])a1]}^)^)W)Y3Y+W)V)X4Y)W)_)`0^}^)_)V)X/^+W)V)b+X)V)`)_1^}^)`*W+d*W*d+W*a)_0_}^*`*V+d*W*e*V+`*^0`}^)V+Z+V)V*f)W)f*V*V+Z+V)]1`}^)Y-Y)V*f)W)g)V*Y-Y)]0a}]/])V*yZ*]/[0b}\\)\\)[*V)y[)V)[)\\)Y1b}[)^)Y)V)y])W)Y)^)X0c}Z)`)V*W)y])X*V)`)V0d}Y)b)Z)h)W)h*Z)b1d}Y)b)Z*g)W)h)[)b0e}Y)b)[+e)W)g)\\)a0f}Y*`*\\)V8Y:]*X+Y1f}Y)V+Z+V)\\)yW)])V/X0g}[)W-Y)\\)yW)])[,W.h}Y1Z)\\)e)Y)e)])X0W-h}X4`)f,f)^)X)W.W*i}X5`)f*f)`)V)Z-l}V8_)y)a*V,W-j}V7a)e*e)c/W-i}V1X,a)b)V*V)b)c2W-g}V3W+a)a*Y*a)c3W)V*g}V4W*b)s)d9g}V5V)d)q)f6i}V5V)eDg6i}W5e)r)e5j}W5e)b*c)f3k}X4d)b)W)c)g/m}Y2d)b.b)c,X)V)n}[/e)a)[)a)c,t}\\-e)a)V.V)a)c)v}q)_*V)[)V*_)ya}p)^*Y.Y*^)y`}p)^*Y.Y*^)y`}o)^)\\)W)\\)^)y_}k)W)^)^*^*])W)y[}j)V*[,l+[*V)yZ}j)\\*s*\\)yZ}k/e*e/y[}q)d)W)e)y`}q)d)W)e)y`}q)c)Y)c)ya}r)b)Y)c)ya}r)a)[)b)ya}s)`)[)a)yb}s)_)])`)yb}s)_)])`)yb}r6[6yb}r)a)[)yo}s)`)[)a)yb}t)_)[)`)yc}u)^)[)_)yd}v)])[)^)ye}w)\\)[)])yf}x)\\)Y)])yg}x+Z)Y)[+yg}w*\\)Y)]*yf}m)[+^*W*_+Z)y]}l*Y*b)W)c)Y*y\\}k)W,d)W)d,W)y[}k)g,W,g)y[}k)a._/`)y[}k5l4y[}yyyY}yyyY}~~~";
if(argument0 == 26)
    mydata= "yyyY}yyyY}v.c.yf}u0a0ye}t2_2yd}t+X-]-X+yd}s+Z,],Z+yc}s*\\,[,\\*yc}s*V*Z+[+Z*V*yc}t*W)Z+Y+Z)W*yd}y)Z*Y*Z)yi}yV)Y*V)W*Y)yb)\\}yW)X*V*V*X)yd)[}y^*W)yg,Y}yW.V*Y+yd+Y}yV/V+[)yb-X}yV0V+Z)yc-W}f)h1V+W)j)r.W}f)h2V-V)h)s.V}e*h*_+k*q/V}e)V)g*d)g)V)q/V}d)W)g*b)V)g)W)p/V}d)W)g*b)i)W)o0V}d)X)f.Y-W)f)X)n1V}d)X)f/W)\\)f)X)o/W}c)Z)e/W)\\)e)Z)m1V}c)Z)f.W)[)f)Z)m0W}c)[)e.W)[)e)[)l0X}c)\\)a*V.W)Z)W*a)\\)k1X}c)])^*Y-W)Z)Y*^)])l/Y}d)]*[)[-W)Y)\\)[*])l1X}b+^/],W)Y)X+W/^,i0Y}a)W)])])[,W)X)\\)])])X)g0Z}`)Y)[)W/]+W)W)^,Z)[)Z)e1Z}_)[)Z)V)e*W)V)h)Z)\\)d0[}^)])X)i)W*j)X)^)b0\\}^)^)W)Y3d4Y)W)_)a1\\}^)_)V)X/s+X)V)`)a0]}^*_*W+y+W*`*`0^}^)V+Z+V)V+yV*V*V+Z+V)_1^}^)Y-Y)V*yW*V*Y-Y)_0_}^)b)V*yX)V*b)^0`}_)`*V*yZ)V)`)^1`}]/[)V)V)y[)W)[/\\0a}\\)\\)X*W)y])X*X)\\)Z0b}[)^)[)y])\\)^)X1b}Z)`)[)h)W)h*[)`)W0c}Y)b)Z*g)W)h)[)c0d}Y)b)[+e)W)g)\\)b1d}Y)b)\\)V8Y:])b0e}Y*`*\\)yW)]*`0f}Y)V+Z+V)\\)yW)])V*V+W)V1f}Y)Y-Y)\\)e)Y)e)])X-X0g}[*_)\\)f,f)])[,W.h}Y1c)f*f)_)W)V.W-h}X4a)y)`)W)X-W*i}X5a)e*e)c)Z.k}W7a)b)V*V)b)d)V,W-j}V7b)a*Y*a)d/W.h}V1X,b)s)d2W-g}V3W+c)q)e3W)V*g}V4W*dDf9g}V5V)d)r)e6i}V5V)d)b*c)e6i}W5d)b)W)c)d5j}W5c)b.b)f2k}X4c)a)[)a)g/m}Y2c)a)V.V)a)b,X)p}[/d)_*V)[)V*_)b,t}\\-d)^*Y.Y*^)b)v}o)^)\\)W)\\)^)y_}o)^)\\)W)\\)^)y_}k)W)^)^*^*])W)y[}j)V*[,l+[*V)yZ}j)\\*s*\\)yZ}k/e*e/y[}q)d)W)e)y`}q)d)W)e)y`}q)c)Y)c)ya}r)b)Y)c)ya}r)a)[)b)ya}s)`)[)a)yb}s)_)])`)yb}s)_)])`)yb}r6[6yb}r)a)[)a)yb}s)`)[)yo}t)_)[)`)yc}u)^)[)_)yd}v)])[)^)ye}w)\\)[)])yf}x)\\)Y)])yg}x+Z)Y)[+yg}w*\\)Y)]*yf}m)[+^*W*_+Z)y]}l*Y*b)W)c)Y*y\\}k)W,d)W)d,W)y[}k)g,W,g)y[}k)a._/`)y[}k5l4y[}yyyY}yyyY}~~~";
if(argument0 == 25)
    mydata= "yk}i)`)\\)f}h*_*\\*e}h+\\-Z,d}g,[.W/d}]*]-Y9[)\\}]+[/V=W+\\}],YK\\}]-XK\\}]-WLV)Z}]>X<Z}];Z-Z3Z}\\:[,[4Z}\\9\\+[/V-W)W}[:e.W-V*W}X)W:f*Z0W}X:p0W}W7s1W}W5t3V}W3u4V}W1w4V}V1y3V}V0yW2V}V/yY1V}V/yZ0V}V.Y.v/V}V.X/n-X/V}V.X0m-Y.V}V-Y0l/X.V}V-Y0l/X.V}V-Y0l/X.V}V-Y0l/X.V}V-Y/W)h)V/X.V}V-Y/V+f*V/X-W}W,Y/V,d+V/X-W}W-Y.V.a,V/X-W}W-Y.V._.V/W.W}W-Z,V0V/V/V-X.W}X-Y,V/V0V/V-W/W}X.Y+V/V0V0V+X.X}X/Y)V0V0V1V)X/X}X0Y1V0V1Y0X}Y0Y0V0V1X0Y}Z0Z.V0V.Z0Z}Z1[+V2V+Z1[}[2m3\\}\\4f5^}]L+`}_Kb}aGd}f=i}`1Z)])W4^}[-Z)\\)])])[+[}Z)^)\\)])])[)X)Z}Y)^)\\)])])[)Y)Z}Z)\\)\\)])])[)X*[}[,W)\\)])])[)W*]}_L*_}yk}bGc}a)W)\\)^)])V*a}`)W)\\)^)])X)a}`)V)\\)^)])Y)a}`*\\)^)])Z)a}a)[)^)])Z)b}b*X)^)])Y*c}dCe}yk}dCe}d)[)])\\)V)e}d)Z)])\\)W)e}d)Y)])\\)X)e}e)W)])\\)Y)e}e)V)])\\)Y)f}f)])\\)Y)g}g=h}yk}i9j}h)X)[)[*h}g)X)[)])h}g)W)[)\\)V)h}g)V)[)\\)W)h}h)[)\\)W)i}i)Y)\\)W)j}j7k}yk}j7k}j)Y)\\)V)j}i)Y)\\)W)j}i)X)\\)X)j}i)W)\\)Y)j}i)V)\\)Z)j}j)\\)Z)k}k5l}yk}m1n}l)\\)V)m}l)[)W)m}l)Z)X)m}l)Y)Y)m}l)X)Z)m}j)V*V)Z-j}g)V<g}f1Z+W-f}d-Y+Y*Y.d}c/X+Y+X/c}a1X*X)W*X1a}`6V*W*V5a}`4W*Y*W4`}_4W)])W3`}_3V*_*V3_}^2W*a*W1_}^1W)e)W0_}_.W*g*W._}^.W)k)W-_}^-V*m*V-^}^+W*o*W+^}^*W)s)W*^}]*V*u*V)^}_*w*_}yk}yk}~~~";
if(argument0 == 24)
    mydata= "yc}yc}h9c}e+t}y)b}c*g)V)b}c*V)V)V)[*W-b}b1[*W-b}b1[*W-b}b1[*W-b}a2[*W-b}a2[*W-b}a2W)X*V.b}`3W)X1b}`3V*X1b}_7X1b}_7X1b}^8X1b}^8X1b}]9X2a}]9X2a}\\:X2a}\\;V4`}[I`}[J_}ZK_}Z/W*W0W*W1^}Y0W)X0W)X2]}Y1X3X5\\}Y2X3X5[}X1X)W0X)W5Z}X1W*W0W*W5Z}XL/Y}WL0Y}W2V)V8V)V5X}W0V)V)V*X+Y*V)V)V5X}V3V+V+V)V,V+V8W}V7X*V*Y<W}V7V2V<W}V7a=V}VL4V}VL4V}VL4V}VL4V}VL4V}VL4V}VL3W}WL2W}WL1X}WL0Y}XL.Z}XL-[}YL+\\}[K^}^+g+^)\\}^+Z)X)]+Z)X)\\}^+Z)X)]+Z)X)\\}^+Y)Y)]+Z)Y)[}^+X)Z)]+Z)Z)Z}],X/],Y.[}\\-g-d}yc}~~~";
if(argument0 == 23)
    mydata= "yb}yb}yb}i-V*j}g0V,g}f1V-f}e3V-e}c5V.d}a7V/c}_2V,Y.c}^:V/c}];V/c}\\;V0c}\\;V/d}[<V-f}[;V-g}[;m}\\2u}yb}r*g}q+g}n/X,_}l0W/^}l/X._}k/W.a}k-W1`}j+a)a}j)Y0d}i7c}i5V)c}h)X+V,Y)b}h,]*V+a}g0V2a}f=`}f=`}e?_}e?_}e?_}e?_}f=`}i7c}yb}yb}yb}q)i}o+i}n,i}n,i}n,i}i1V-c}g;a}h9b}yb}yb}~~~";
if(argument0 == 22)
    mydata= "p*b*q}o*d*p}o*d*p}o+W1W+p}o+V3V+p}p*V3V*q}m*X5X*n}lAm}kCl}k3V+V3l}j,V.V-V.V,k}j,V)Z/Z)V,k}j,V;V,k}i-V.V-V.V-j}i-V*V+V-V+V*V-j}i-V+Y-Y+V-j}i-W+X-X+W-j}i-W+V1V+W-j}i-W9W-j}i.W7W.j}i.W-V+V-W.j}i.W7W.j}j-X5X-k}e*X-Y)V/V)Y-k}c,X.X*V)X)V*X.k}b,Y.Y1Y.k}a-X)V-Z/Z-V)j}a-X)V,g+X)j}a,Y)r)X)f}`-Y)X.`-Y)X*e}`-Y)[*Z+X,[)X+d}`.X)Z*X)Y*V.Z)X,c}_/a+W)W)V,\\)X,c}_0X+Y+X*X*])V)W-b}_8V+X+b)V)W-b}^:V1`)W)W-b}^:V1`)W)X-a}^;V0_)X)X-a}^;W/W)\\)X)X.`}^<V.W+Z)Y)X.`}^<W+Y+Z)Y)X/_}^0[/d)Z)X/_}_-a+d)Z)X0^}_,X.Z)Z+\\)Z)Y0^}_,W)[,\\+\\)Y*Y0^}`*W)h)\\)X+W)W1]}a)W)`*b)X+W*X0]}d)b)`)X+W)V)X0]}d)c)^)X+W)W)X1\\}c)e)[*X+W)Y)W1\\}c)h,Y,V)Z)X0\\}c)e)]/[)X0\\}c)d*\\.])X1[}c)d*[.^)X1[}c)c,X.`)X2Z}b)c,W-d)W2Z}b)c*Y*g)W2Z}b)b*n)W3Y}b)b)o)W3Y}b)yY)W3Y}b)yY)W3Y}b)yY)W4X}b)yY)W4X}b)yY)W4X}b)^,p)W4X}b)b+m)W4X}c)d*k)W4X}c)Z-r)V*],W}d5n)W)W-X+W}c;i)Y0W*W}b;V)g)Y2W*V}b*V+V2Y*a,Y/V,W)V}b*V+V+b4\\+X+V*V*W}c)V+V*yc}yy}yy}~~~";
if(argument0 == 21)
    mydata= "ye}m)p}n)o}i*X)W+j}e+X)W)V)Y+f}h)W*V)V)W*i}c-V)W)V)V)V)W-d}b)Z)V)V)V)V)W*Z)c}c,W)W)V)V)V)X,d}a*Y)W)V)V)V)X*Y*b}`)\\)V)V)V)V*V)])a}i)W)V*V*^)a}j)V*V*V*j}j)W)V*V)k}m)V*m}c+e+e}`1`0b}_G`}^I_}]J_}]?X1^}\\?Z0^}\\1Y1\\/^}\\0[0\\/^}\\0\\/\\/^}\\0\\/X3^}\\0\\/W4^}]3X/W4^}]4W/W3_}]4W<_}^3W<_}^H`}^H`}^6W2W,`}_,X.W*W.W,`}_-X,W+W-W,a}`,X2W+W-a}`-X6W,b}a,Y4W-b}a-X3X,c}b-X2W-c}c-W1W-d}c-X/X-d}d-Y*Z-e}d._,f}e-^-f}f-\\-g}f.X)V.g}g7h}h5i}i3j}j1k}k.m}ye}ye}~~~";
if(argument0 == 20)
    mydata= "ye}ye}w+d}a*j,b}`*l,a}_+l-`}^+n,`}],n-_}\\-n-_}\\-^1\\-_}\\-[7Y-_}\\-Y;W-_}\\.WC_}\\K_}\\6_3_}]2d0`}^/h.`}^.j-`}].l,`}]-m-_}]-n,_}\\-o-^}\\,`._-^}\\,^1_-]}[-]+[*^-]}[-]*])^-]}[-\\*_)].\\}[-\\*Y*Y)].\\}[-\\*X)W)X)].\\}Z.\\*X)W)X)].\\}Z.\\*X)W)X)]/[}Y/\\*Y*Y)\\0[}Y0\\*])]1Z}X1\\+[*]1Z}X2\\1]3Y}W3^.^+X-Y}W-Y+k*[-X}V-\\)k)],X}V,^)i)_,W}V+`)g)a+W}V+a*c*b+W}V+c6d+W}V+e2f+W}V+y\\+W}V+y\\,V}V.yX-V}V/yV.V}W.a)\\)e*V+V}X+V)a)V)X)W*c)W+V}X)V)a)V)V*V+V*Z)])W*W}X)V)e+V*])_*X}X)`)i)d}d)i)d}d)h*d}d)g*e}d*e+e}c,d.b}a.c0a}`0b0a}ye}ye}~~~";
if(argument0 == 19)
    mydata= "ye}ye}b+f+e}a-d-d}_/c*V,c}^-W*b)X,b}]-Y)a*Y,a}]+[*`)[+a}g)`)\\*a}g*^*j}h)V/V)k}g)W/m}f*X-X)j}e,W-W+i}d:h}c<g}c<g}b*[.[*f}b*\\,\\*f}b*]*]*f}a+g+e}a,\\*\\,e}]+V
e}\\+V/W)V)V)V)W/V+a}[+W-d-W+`}[*X,V)b)V-W+_}[*X,V+V/V,V,X*_}[*X-X1Y-X*_}[*XBX*_}[-]1_,_}[,_/_-_}`-Z-Z.d}`-W)W-W)W.d}`.W)V-V)W/d}`Bd}a
e}a+f,e}a
e}b)i)f}b*g*f}c<g}d:h}ye}ye}ye}g*\\*l}g*\\*l}g*\\*l}c.\\.h}a0\\0f}`0^0e}ye}ye}~~~";
if(argument0 == 18)
    mydata= "yd}yd}yd}d.X+W,g}b*[)V)W)V)Y*e}a/W)V)V)V)W/c}h+W)W+j}_1\\)X1a}^)],\\+\\*_}])W/c.X)^}\\,p*W)]}[*X1_0W)W)\\}[)V+Y*c*Z*V)W)[}Z)V)Y*Y+W*Y)X+Y)V)V)[}Y)V)Y)W.W+V*W+X)Y)V)V)Z}Y)V)X)V*Y*V,V+W-V)Y)V)V)Y}X)V)X)V*Z)V*W)V)V*W-V)Y)V*Y}X)V)W)V*Z)V*X)V)W*V)W*V*V)V)V)V)X}W)V)X)V)[)V)Y)V)X)V)X*V)Y)V)Y}W)V)X)V)V*X)V)Y)V)X)V)Y*V)X)V)Y}W)V)W)V)W*X)V)Y)V)X)V)Y*V)V)W)V)X}X)X)V)V+X)V)V)W)V)X)V)V*W)V)V)W)V)X}X)W*V)V)Y)V)W)W)V)V)V)V)W)W)V)Z)Y}W)X)V*[)V)V*W)V)V)V)V)W*V*V)Y)Y}W)X)V)[)V)W*W)V)V)W)V)W)W)V)Y*X}W)X)V)W)X)V)W)X)V)V)W)V*V)W)V)Z)X}W)X)V)V)Y)V)[)V)V)X)V)Y*V)Y)X}X)V*V)V)Y)V)[)V)Z)V)Z)V)Y)X}X)V)V*V)X)W)V)X)V)[)V)W)W)V)X*X}X)V)V)[)V*V)X)V)[)V)W)X)V)W)Y}Y*V)[)V)W)X)V)W)X)V*Z)V+Z}\\)[)V)W)X)V)W)Y)V)[)]}\\)Z)V*[)V)W)Y)V)[)]}\\)Z)V)\\)V)W)Y)V)[)]}])Y)V)\\)V)\\)V)Y*^}^,W)\\)V)\\)W-_}d)\\)V)\\)f}e)[)V)[)g}f.X.h}yd}yd}yd}yd}~~~";
if(argument0 == 17)
    mydata= "ye}ye}ye}f*g)c}e)W)e)V)b}d)Y)d)V)b}c+X)c)X)a}c+X)c)X)a}j)Z.W)X*`}j)X1V)X+_}j)V4Y*`}j+X*X+f}j)Z*Y+e}i)Z,Y*e}h*Y-Z*d}g*Y.Z*d}g*X0Y*d}f<d}f+V-V.V,c}f0X2c}f0X2c}f/Z1c}b)X.\\0c}a*X.\\0c}`+W/V)W)W0c}_*V)W>W*_}]*X)W>W*_}[*V)W)W?V+_}Z+W+W-W.W/W*V)^}Y*V)W*W-Y,Y.W,^}W,V,X,Z,Y.W+V)]}X-W)X*W+W,V)W.X*V*\\}`+W6W-X-\\}c:W+X*X)[}b=X+W*V)[}b
[,Z}b?e}b)X*X+X0e}g)Y)Y*X*f}ye}ye}k)[)k}k)[)k}k)[)k}k)[)k}i+[+i}h+\\,h}g+^,g}g*a*g}ye}ye}ye}ye}~~~";
if(argument0 == 16)
    mydata= "yi}yi}yi}a/d.e}`1a1d}_3_3c}^5]5b}^,Z-\\6a}],\\-Z.Y.`}]+^,Z-[-`}]+^,Z,],`}]+^-X-],`}]+\\/X-],`}]+Z.W,W/Y,`}]6W,W1W,`}]L)`}[L+`}ZL,`}YL._}X5^*]4^}W3m3]}W1[.Z.Y3\\}W0Y>Y1\\}WL3\\}XL1]}YL/^}ZL,`}\\Kc}`Bh}yi}yi}yi}b,c+k}`Ai}_4V6h}_3X6g}_0V*Y+V1g}_/X)Y*X0g}^0W0X1f}^Ff}^Ff}^1a1f}^/d0f}^.X+Z+X/f}^.W*V)Z)W)X.f}^-X)W)Z)W)Y.e}^-X)V)[)V*Y.e}^-X+\\+Y/d}].X*^*Y0c}Z1\\,_1a}Y2[)Y)^2`}Y1\\)Y)_1`}Z/o.a}yi}yi}yi}yi}~~~";
if(argument0 == 15)
    mydata= "ye}ye}ye}j7e}h+b+c}g*f*b}f*h*a}e*`+\\*`}e*_-[*`}d*`*W*[*_}d*\\)X/Z*_}d*\\*W-\\*_}d*\\1\\*_}d*\\2[*_}d*]1[*_}d*^/\\*_}d*l*_}d+Y)Z)Z)Z*_}e+W)V)X)V)X)V)X,^}].X,X+X+X-W)]}[2W*g*X)]}Z4W)g*X)]}Y6i*X)]}X8h*X)]}W:g*X)]}W:g*X)]}V*X7e+X)]}V*V)V7V)c*Y)X+W}V*V)V.X.V)b+Y)W-V}V*X.V)V.V*_,Z)W-V}V3V)V.V,[-[)W-V}V3X.W4])X+W}V.Y1Y1_)Y)X}W,V,V0l)X)Y}W,V,V/m)Y)X}X,Y/n)X)Y}Y5o+W)X}Z3p)W*Y}\\/r)]}y\\)]}c)q)]}d)o)^}d)o)^}e)m)_}c)W)k)`}c*W)i)a}c+W*e*W)_}c,X+_+X*_}d-Y2Y,_}d,g,`}d,g,`}a/d/`}`1b1_}_)V*Y*a)V*Y*_}_)V)[)a)V)[)_}ye}~~~";
if(argument0 == 14)
    mydata= "yyw}yyw}yyw}yyw}yyw}yyw}p9yo}n9[-yf}l5_)V/yd}k4`+V/yc}j3c+W/ya}j2f+W.y`}i3b*X,V.y_}i3a)W*W+V+yb}h3\\+X*X)W*V*Z)y]}h3[*W)V)W+V)W)V*X+y]}g3])X)V)V,V)V*W-y^}g3]+X)V-V+W)]*yX}g3])W*V)V-V+\\)W)W*yV}g3])Z)V+X+\\)V)W*yW}g2^)Z)[,\\)X)V)yW}g2^)Z,W-\\)V*W)yW}g2^+X,V/Z*Z)yW}h1_)V)W,V*X*Y+Z)yW}h1_)W)V+V*V*W*X+V*W)yW}h1_)V)X-V)X+W+X)V)yW}h1_+X-[+V+Y*yW}i1^+X,Z*V.V)W)yX}i1^*Z+Z*V-X)V)yX}j0^*Z+[)W,X*yY}k0])[-Y)W,X*yY}m/\\)[,V*Z+Y*yY}p.b,\\+Y*yY}yb,W,Z)yZ}t0Z*V)Z*V*ya}m;X*\\*yb}l0]+V+W*X+yc}l+c)V*c)X*Y0s}m+d)d*Y:m}n+c)b*W,V+]0k}o)V*a*g+V)c+k}p)W*`)h*d+l}q*W+]*g)d+m}s*X-Y)f*b*V)n}u+Z)Y)e)a*W)o}d-d.W)W*b*^+W*p}c0\\)^,Z-])Z-X*r}b2Z-])g)Z)Z+t}b2Z1X)]*\\*W*W.c.c}b0W)Y4_0[,^)\\0b}a2Z3p)]-Z2a}a3Y3g*])X1Y3a}a3Y2e,_4Y)V1a}a4X2W)b)e2Z1a}a4X1Y)a)f1Y2a}a5X0Y)`*f1Y1b}a,W/Y/Z)_*b)Y0X2b}b+W0Y-[*Z.a)Z0X2b}b+W1Y,\\-[*`)Z/X1V)b}c*W2X,\\5_)[.Y/V)V)b}c)Y1X+]+X4Y*Z.Y0V)V)b}h2W+],\\)[-[-Y1V)V)b}h2W*^-[4[,Z1X)b}h3V*_-Z.X+[,Y1W)d}h2X)_-Z)\\,[,X2g}i0f+Z)[-[,W3g}i0b)`)Z-\\+X3g}j.b.\\)Z-])Z2g}j.b2X)Z+X)b0h}j,V)b6_+[)Z0h}j,d)V3^-a/i}k*d*Y0Y2a/i}k*d+[<`,V*i}k)d*W*^7`,V)j}yW)Z+[3X)a*m}k)c,[6[*`*m}yV*W*`)_*V)`*m}yV*Y+[)V)\\+X)a)m}y+\\0V/[)a)m}y,_+V)`,y}y)W+[1[+W*y}x*Z.Y3Z+x}x)_)[/\\,x}x)_)W4Y+W)x}x)^)W-W+W-Z*w}x)])W.])^)w}x)\\)W/])^)w}x)[)W0Y*X)])w}x)Z)W1W-X)\\)w}x)Z4W-Y)[)w}x)Y)^+W.X)[)w}x)W*a)W-Y)[)w}y*g,Y)[)w}yW)c)X*Z)Z)x}yV)d)X*[)Y)x}yV)d*W*[)X)y}yV)e)W*V+W)W)yV}yV)e)W.X*yW}yW)X1X)W.y\\}yW)V-X,W)V/X)yX}yX+],W.y]}yX*`*W.y]}yX)Y-X*V/y]}yX)V+Y+V)W/y]}yY*^)W/y^}yY*_)V/y^}yY)W0V)V/y^}yY)V2W/y^}yZ4V0y]}yZ4V0y]}vFy\\}rJy\\}mL.yY}yi:u}yl=o}yyw}yyw}~~~";
if(argument0 == 13)
    mydata= "yc}yc}b+Z+[,X-]}a-X-[,X-\\}a-X-[,Y,\\}a-k,\\}i-X,V+X-[}a-X-V/V,V-[}a-X-V/V,V-[}a-V/V/V,V-[}a-V3V,V1[}])X8X+V1[}\\)V)X6Y+V0\\}\\)V)X6Z*V0\\}[)X)W*_*Z*V/]}[)Y)V)V2\\)V3Z}[)Z)V)_)],W/X}[)Z)W2[)^/W}[)[5Z)`.V}[)Z7Y)a-V}[)Y8Y)Y-Z+V}W-Y,X)X-Z)W1[}V.X,V+V+V,Z)W2Z}.Y,V/V,Z)W3Y}.X:Z)X2Y}.X1V0Z)X2Y}-V)W5V)V*Z)Y1Y},X)V+V)V0V+Z)Y1Y},Z,V0V)V*`)X+Z}V+Z+V)V4`)`}X)[8a)`}X)[6c)`}X)\\4d)`}X)]2e)`}Y)]0e)a}Y)^.f)a}Y)_,g)a}Y)`+g)a}Z)`)g)b}Z)s)b}[)q)c}\\)m)V)d}\\)W*g+V)d}\\)W,`*X+V)d}\\)X*Y)X,V)Y)W)d}])W)Y)V)W)Z)[)d}])[)X)W)Z)Z)d}])Z)Z*V)Z*X)d}])X*f+e}^+yW}yc}~~~";
if(argument0 == 12)
    mydata= "yyc}yyc}yyc}yyc}yyc}yyc}j+y+l}j,\\+[*[+\\,l}j-Z-Z*Z-Z-l}j.X.Y,Y.X.l}k.W-Z,Z-W.m}k/V,V*X,X*V,V/m}k4V+W,W+V4m}l4V0V+V4n}l4W2W4n}m3X0X3o}h7Z.Z7j}g2W,[,[,W2i}g2Y*[,[*Y2i}g3Y)[,[)Y3i}h,V-`,`-V,j}i*V)V-_,_-V)V*k}j)V*V-^,^-V*V)l}l+V*W)],])W*V+n}f,X*V+_,_+V*X,h}g,W*V,^,^,V*W,i}h0W+],]+W0j}j0W)],])W0l}j2].]2l}i6Z.Z6k}h,X2W0W2X,j}c-^D^-e}a8Y<Y8c}`=Y4Y=b}`+V<W2W<V+b}`*X<W0W<X*b}`+V=W0W=V+b}`AW0WAb}`-X:W.W:X-b}a+Z9W.W3Y*Z+c}a+Z-Y0W.W0[+Z+c}a,X-W*X.W.W.X*W-X,c}b2W-X,W.W,X-W2d}b2W/W+W.W+W*W+W2d}c.Z+W+V+W.W+c.e}d.b+W.W+b.f}e0_+V0V,^0g}f/W.W*V,W,V2W/h}g.V0V)V,V*V,V2V.i}h7V,V,V,V7j}i5V,V.V,V5k}j3V,V0V,V3l}k)W.V,V2V,V.p}l)Y*V,V4V,V*Y)n}m,W,V,W*W,V,W,V)m}g.V0V,W,W,V0V-j}e1X,V)V+W,W+V)V,X0h}d4V+V)X*W,W*X)V+V3g}d3V,Y)V2V)Y,V2g}e1V*V*Y*V0V*Y*V*V0h}i,V*W*Z)W.W)Z*W*V,k}l)X)V*^,^*V)X)n}k.V*])V*V)]*V.m}i0V*]*W*]*V0k}h1V*]*W)^*V1j}g3V)^)])X)V3i}f4X)d*V)X4h}f4X*W)`)V*X4h}e0V-X*V*`*X-V0g}e.X.X*V)_*X.X.g}d.X0X*_*X0X.f}d+Z0W*V*V*Z*V*W0Z+f}k0W+W*V)V*V*W+W0m}j0W,X*W)V*X,W0l}j/Y*V)X*W*X)V*Y/l}i-Y*X*Y,Y*X*Y-k}i+Y1V)X*X)V1Y+k}p1V+Y+V1r}p1V2V1r}p1W0W1r}p1V)])V1r}p1V2V1r}p1V2V1r}q0V2V0s}q0W0W0s}r/V)])V/t}s.V2V.u}t-V2V-v}s)V,V2V,V)u}r+Z2Z+t}q+k+s}p+m+r}o+o+q}k*V+q+V*m}l,s,n}m+s+o}l-q-n}k+W*o*W+m}j+Y*m*Y+l}yyc}yyc}~~~";
if(argument0 == 11)
    mydata= "yc}yc}p+i}n*X)h}m)[)g}l)\\)g}l)])f}l)])X+`}k)^)W-_}k)X*Y)W*W)_}d-W)W)W)Y)V*W)_}c)Z)V)V)])W+`}c)[)W)^+b}yc}g-W+k}d.[+i}b.X+Y+g}a*V,W-V)W)V)f}`)W*Z-V*W)V)e}_)W*W)V)W-V*W)V)d}^)X*V*V*V-V+W)V)c}^)X)W*V*V-V+X)V)b}])X)W+V*V-V,W)W)a}])X)W*W*V-W,W)W)`}\\)X*W*W*V.W+W)W*_}\\)X*V*W+V.W,W)W*Z,}\\)X*V*W+V/V,W)W+W.}[)X+V*W+W.W+W)W2V}[)X)V)V*W+W.W+X)W1V}[)X)V)V*W+W/V+X)W1V}[)X)V)V*W,V/V+X)W0W}[)X)V)V*X+W.V+X)W*W)Z}[)X)V)V*X,V.V*Y)W+V,W}[)X)V)V+X+V.V)Z)W)Y,V}[)X)V)W+X*W-\\)W*V)V,V}[)X)V)X,W)W-\\)W1V}[)X)V)Z*[,\\)W+V.}[)X)V)c*])W*Y,}[)X)V)m)V)_}Z)Y)W)k)V)`}Z)Y)W)k*a}Z)Y)W)j)c}Z)Y)X)h)d}Z)Y)X)e+e}Z)Y)X)x}Z)Y)Y)w}Z)Y)Y)w}[)X)Y)w}[)X)Y)w}[)X)Y)w}[)Y)X)w}[)Y)X)w}[)Y*V)x}\\)Y*y}]-yV}yc}yc}yc}~~~";
if(argument0 == 10)
    mydata= "Z2[}Y4Z}X6Y}W8X}V)W7W},V7V},W6V},X5V},W)V+\\*V},W/W-V},W/W-V},W/W-V}+X.Y)V*V}V/V0W)V})W,W/V*W})V-X.V)X}V)V,V)V.V)X}V)V4W)X}X4W)X}Y2X)X}c)W)X}Y*V*V*V*W)X}Y*V*V*V*W)X}Z)V*V*V)X)X}f)X}f)X}e*X}Z)V)V)V)V)V*Y}\\)V)V)W+Y}Y*\\+Z}Y3[}j}j}j}j}~~~";
if(argument0 == 9)
    mydata= "yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}yyW}y].m}d+V)k*V+o}c-j*W*X,j}c-m*W0h}c-l*^+g}d,k*X.X*]+[}d-i+V1X+W,X)Z}d.g+W2W0Z)Y}^+Y.f*W3X-\\)Y}\\,Z/d+W4W+c}Z.W)X/b+W5h}Y/W*X0^-W5h}Y.X+X1X0V)V5h}X/W-X:V*V5h}X/W.X7W+W4h}X/W/W*V2W-W3i}X/W0V*V0W0W2i}Y.X/W*V)V+W2X0j}Y.X0V*W)W)V4X-l}Z.X0V)V,V*Y0\\)k}[-X1V)V/W0Y-k}\\-X1W9X*o}Z*W+X9W)V.[+l}[*]AZ,m}Z)W)^6W.[,m}Y+a;],m}X,c6`,m}W,yY+n}W,yY+n}V,i.d+n}W)W8Y/c+n}X8_*d+n}[0[+l+n}h-X)g+n}h-W+g*n}k*W,f)o}o,f)o}i*Y,e*o}^)W+X-X,e)p}^*V3X,e)p}],X/W)j)V)n}_,X,W+i)V)n}a0X/e)V)n}b/W)X2_)V)n}d,X,X/_)V)n}j)V.Y+_)V)n}i*V2b)V)h*Y}i*W3`*e.Y}i+W0b)W*^2Y}i+Y,W*b+X5\\}i+^+a+X5]}i+^,_+X6]}i*`+_+W5_}i*`+a)V3b}h+`,b0e}h+a+b1d}h+a,c2a}g+c+e/b}g+W+^,x}g+Z+\\+W)u}h*[)^)Y)t}`*b*b*t}b,[-a,s}b6[)Z-s}c-Y,Z)Z+V+r}c+Y.Y*X,X*r}d4Z/X,q}e,Y+[-V)V*V*q}e*Z,\\0W*q}f2]-X,p}f2^-V-p}g)Z,^1q}n+_/W1g}h1`-W3f}b8_,W5e}`:_-V5e}_;_<d}^<_<d}^<`;d}^8d;d}_5l4e}yyW}yyW}~~~";
if(argument0 == 8)
    mydata= "yt}yt}yt}yt}yt}yt}yt}yt}l)V)d)V)l}l*V)b)V*l}l+V)`)V+l}l)W)V)^)V)W)l}l)W)V)^)V)W)l}l)X)V)\\)V)X)l}l)X)V)\\)V)X)l}l)X)V1V)X)l}l)h)l}l)i)k}l)i)k}k)j)k}k)W.X.Y)k}j*V*X*X*X*X)k}f,X/X/X)k}a1Y*`*X*k}`)X.])Z)[+b+[}`)X/])X)Z-b+[}`)W9X3b+[}aIb+[}a<Z)V.k}b4\\*V*V/^/[}c1X*V*V*V)W/]1Z}r*V)Z/\\2Z}l-[,V.\\2Z}m=\\2Z}n:^1[}q5`+a}y^)[+V0X}y]*[+a}p)d+[-V)V)[}p*c,Z-V)V)[}o+X0X-Y-V)V)[}n,V4V-Y-V)V)[}j)W-V4V,W)W-V)V)[}k)W,V4V,V)X-V)V)[}c2V,V3W,V1V)V)[}b3V,W0Y,V1V)V)[}b3V,Y-Y-V1V)V)[}b3V-W/X-V1V)V)[}b3V-X.W.V0W)V)[}b.W+V.W-W/V+\\)V)[}b-Y*V/W+W0W*\\)V)[}b-X*W1X2X)\\)V)[}b-X)Y=`)V)[}b-].V-V0`)V)[}b-]-V)V+V)V.a)V)[}b-^,V*X*V.a)V)[}b-^,V/V.a)V)[}b-^+V*V+V*V-a)V)[}b-^*W+X+W,a*\\}b-W)[*V*V*V*V*V,a*\\}b-W)[*W*Z*W,a*\\}a-X)[,V)V+V)V.a)]}^)V.V)V.V,V)Z)V.V/Y)]}^)V.V)V.V,V*X*V.V0X)]}^)V.V)V)[-V-V/])a}^)V.V)V.V.Z0V/b}`-Y)[;j}a+V*W)^4n}p+a.h}p-W)W)W.j}o/V)W)V0i}t*[,m}p,a+j}p<i}p<i}o.W2W*h}o9X*h}o*W/X+X+g}n*X/X1g}n*W<g}mAg}m>W)g}m>W)g}m-X,W0W)g}m-W-W+W.g}m3Y*W.g}m2Z2g}n*W,\\1g}n*W+^,W)h}n.X-X+W)h}o-W/X-h}o-W/X,i}o-W0W,i}o,Y/W+j}o,Y/W+j}x.o}o)V)[.W)V)j}o)V)\\-W)V)j}o)V)],W)V)W*X)b}o)V)^+W)V)W.b}yY)^,b}n-a.Y)c}l*Z)`)Z*f}k)])_)\\)e}k)W)W)W)_)Y)V)V)d}k)W)W)W)_)Y)V)V)d}k2_2d}yt}yt}yt}yt}yt}yt}yt}yt}yt}yt}yt}yt}yt}yt}yt}yt}yt}yt}yt}~~~";
if(argument0 == 7)
    mydata= "yyyY}yyyY}yyyY}yyyY}yyyY}yyyY}yyyY}yyyY}yyyY}yy[0o}yyX5m}yyV9k}yy:V)i}yx;V*h}yx,V*V3V+g}yw-V*V2V-f}yw)V+Y+V.V.e}yv+V)V,V)V/V.e}yv,V*W*V0V/d}yv+V*V)W*V.V0d}yv+V)V)Y)V.V1c}yv+V)V)Y)V.V1c}yv+V*W)V*V.V1c}yq1V*W*V/V1c}ym6V,V0V2b}yl*W4Y1V2b}yk*Y
V2b}yk*Y
V2b}yk+WAV2b}ykFV2b}ylEV2b}ymDW1b}yo>[1b}yyg0V*`}yp)^.a/X*^}yq)]+e-[)]}yp-Y)i+])\\}x)n*Z)d.c)\\}w*l*i+Y*d)[}v+k)i*^-_)[}v,i)yV+\\)[}u-i)yY*Z)[}n+Y.g)y\\*W)\\}o,V0f)y]+]}o,V2yn)^}p*W4yl)^}s8f)c*V)j)]}s;b)d,j)]}r>`)e*l)\\}i)\\>a)a)q)\\}i*Y>c)a*b)b)\\}iBe)a0])b)[}i2V6W)c)b0])a)[}i2W4W+b)b)Z*])b)Z}i/V)V*V2X-a)`*Z*V)\\)a)Z}j/V)V)V2X/_)].W)V)V*\\)a)Z}j.W+V1Z0X+W)\\)V-V*V)V*\\)b)Y}k/X2\\/V-^0W*V*\\)b)Y}k<^,V-V+[)V)V/V+\\)b)Y}l;`*V,V-_.V+[)c)Y}l;a)V+V-V)e*Z*e)X}m;b0V+h+g)X}n:b/V,f*j)X}o:a/V,e)l)X}p:a3V)yW)X}q:`3V+`*l)X}r*d)`1V.\\,k)Y}t*c)`/W0Y.j)Y}v9`+Z1V/i)Z}y,_*h/V0g)[}yX+_)i,V1f)\\}y[2Z*Y)`*V2c*]}yl,V)b3`*_}yr)a+V0]*a}yr)b)V2Y+c}yr)d3V*f}yq)e,V-j}yp)h*V-W+e}yp)l+W.c}yo)r/b}yo)t.a}yo)b,f,`}yo)a)Y)b)f}yo)`)[)`)g}yp)^)])_)g}yq)])])^)h}yr)\\)])\\*i}ys)\\)[)\\)k}yt*Z)[)Z*l}yv)V-Y-V)n}yyW*Y*s}yw,W)Z,o}yyV*[*r}yt.W)Y)W.l}yr0W)Y)W0j}yq)V*V,V)[)V,V*V)i}yq)V*V+V)])V+V*V)i}yy)_)q}yq0a0i}yyyY}yyyY}~~~";
if(argument0 == 6)
    mydata= "yyyY}yyyY}yyyY}yyyY}yyyY}y[+yt}y\\+ys}y[-yr}yY/yr}o=yr}m>ys}k?yt}i)V=yv}h*V;yx}g+V;yx}f-V/_*yw}e.V/_*yw}e.V1V,V-yv}d/V0V*W*V,yv}d0V.V*V)W*V+yv}c1V.V)V)Y)V+yv}c1V.V)[)V+yv}c1V.V*V)W*V,yu}c1V/V*W*V1yq}b2V0V,V6ym}b2V1Y4W*yl}b2V
Y*yk}b2V
Y*yk}b2VAW+yk}b2VDV)yk}b2V>V)V)V)ym}b1W>V)V)V)ym}b1Z;V)yq}c0yyg}`*V/`.^)yq}^*Y-d+])yr}])\\+h)Y-yq}\\)d,d)Z*n)y}\\)b*Y+i*l*x}[)^-^*i)k+w}[)[+yV)i,w}[)Y*yY)i-v}[)W*y\\)g.Y+o}\\+y])f0V,p}])yn2V,p}])i)V*x4W*q}\\)j,c)f8t}\\)k*e)b;t}[)yZ)`>s}[)yZ)a>\\)j}[)b)\\.c)c>Y*j}Z)b)\\0b)e7W1j}Z)a)]*V)V)V)b)c)W5Y0j}Y)b)[)V*Y+a)b+W5Y/j}Y)a)\\*V)V)X-])a-X4Z.j}Y)a)\\*V)V*V-V)\\)_/X4V*X,k}X)b)\\*V*W0\\)W+X0Z3V)V)X+k}X)b)\\+V2_-V/\\3V+W+l}X)b)\\+V.`+V-V,^4X-l}X)c)\\*f-V,V*`;m}W)e*l)V-V+V)a;m}W)g+h+V0b;n}W)j*f,V/b:o}W)l)e,V/a:p}W)yW)V3a:q}W)l*`+V3`:r}X)k,\\.V1`)d*s}X)j.Y0W/`)c*u}Y)i/V1Z+`9w}Z)g0V/h*_,yV}[)f1V,e)X)_+yY}\\*c2V*`)Y*Z2y\\}^*`3b)V,ym}`*]0V+a)ys}b+Y2V)b)ys}e*V3d)ys}i-V,e)yr}d+W-V*h)yq}b.W+l)yq}a/r)yp}`.t)yp}_,f,b)yp}e)b)Y)a)yp}f)`)[)`)yp}f)_)])^)yq}g)^)])])yr}h*\\)])\\)ys}j)\\)[)\\)yt}k*Z)[)Z*yu}m)V-Y-V)yw}r*Y*yyX}n,Z)W,yx}q*[*yyW}k.W)Y)W.yu}i0W)Y)W0ys}h)V*V,V)[)V,V*V)yr}h)V*V+V)])V+V*V)yr}p)_)yyV}h0a0yr}yyyY}yyyY}~~~";
if(argument0 == 5)
    mydata= "ye}ye}ye}ye}ye}ye}ye}ye}ye}y`)Y}y`)Y}y_+X}y_+X}y_+X}y_+X}y^*V*W}y^*V*W}y^*V*W}y^*V*W}y^*V*W}y^*V*W}y^*V*W}y^*V*W}y^*V*W}y^*V*W}y^*V*W}y^*V*W}y^*V*W}y^*V*W}m*^*]*V*W}l,\\,\\*V*W}m,V,V+]*V*W}m,V1\\*V*W}l7\\*V*W}c-Y8[*V*W}_2X2X+[*V*W}]-Y+W-X+X,Z*V*W}Z-]+V-X+X)W)Z*V*W}X,])W+V+V)X3Y*V*W}W*`*W*V6V-X*V*W}V*_,W*W1X*V+Y*V*W}V)`,W*V2X*V,X*V*W}V)W)^,V*V.W+V*V,Y*V*W}V)V+],V*X-\\.X*V*W}V-],V*W-V)[+[*V*W}V,_*W*V)V-V)V*V-Z*V*W}V,_)X*V*V-Y,W)Y*V*W}V,_)X*V*V)V4V)Y*V*W}V)V*_)X*V*W2X+X*V*W}V)V*_*X*V*V)V)V,V*V-W*V*W}V)W)_,V*V+V)W,X.W*V*W}V)W)_,V*V.V*V)V0W*V*W}V)V*_,V*V/V)W1W*V*W}V)V*_,V*V0W,V)V,V*V*W}V)V*_*X*V1V)X*V,V*V*W}W)V)_*X*V.Z.V+W+X}W)V*]*Y*V)Z,V.V*X+X}W)V*]*Y*V2V.V)W*X*V}W)W*\\*Y*V2V.X)\\)}W)W+[+X*V2V/X/V}W)W+W)X+X*V2V/Z)V)X}W)X*W*W+X*V2V/W*V)Z}W)X*W*Y)X*V2V.X*W*X}W)W*X*]*V2V.X*V,W}X)V*X*]*V2V-V)W*V,W}X)\\)]*V1W,W)X)W*X}X)e*V)V.V)[)[)Z}X)e*V*c)[)V)X}Y)e*d*[)V)X}Y)`)Y*b+\\)V)X}Y)`)Y*]/V)[)V)X}Z)_)Y*V3X)V)Z+X}Z)W)Y)W*X*a+V)V)_}Z)W*V+W*X*V5V*V)_}[)V*W*W*X*V2X*V*_}[)W)W*\\*`,V,^}[)W)W*\\*V3X-^}[)W)W*\\*a1]}\\)Z)\\*V3V0]}\\)Z)\\*V4V/]}\\)Z)\\*V5V.]}])Y)\\*V5X-\\}])a*V4[+\\}])a*V.[-W*\\}^)`*\\)X0W)\\}^)`*V.Y0_}_)^*W.Z/_}_)^*V/Z/_}_)^*V.[.`}`)]*V.\\-`}`)]*V-],a}a)[+V,_+a}a)[*X+_+a}b)Z*X+`*a}b)Z*X*a*a}c)Y*X*a*a}c*X*X*a*a}d*V+W+a+`}d.W*c*`}e-t}f+u}ye}~~~";
if(argument0 == 4)
    mydata= "yyu}yyu}yyu}yyu}yyu}yc*ye}yc*ye}yb+ye}yV*_+ye}yV+yq}yV,X2yc}yW*W6Y*y[}yY9W+y[}yX5V-V*y\\}yX-W4y_}yW.W,V0y^}yW8V,y^}yV>y^}yV>y^}yV?y]}yV?y]}yV?y]}yV?y]}yV?y]}yV?y]}yV?y]}y
y]}yAy\\}xCs,]}w3W*W4u*\\}t6W*W7n.\\}kL9g,\\}hL?b-]}g-]6Z7].b+^}f-_4\\5_.a*_}f-X)[4\\5X)[.`+_}_*Z-_6X7_.`*`}^,YLC`*`}]+\\CV+WD`*a}],\\CYCb*a}]*`L9d+a}^*yr*`*b}_*]*c)Z*\\*Z)f+^+b}`*[*d)Z*\\*Z)g+[,c}a0d)Z*^*Z)g3d}b.d)[*^*[)h/f}v)[*`*[)y[}u)\\*`*\\)yZ}t*[*b*[*yY}r,Y*V)b)V*Y,yW}yyu}yyu}yyu}~~~";
if(argument0 == 3)
    mydata= "yf}o)o}o)o}o)o}n+n}n+n}n+n}m-m}m-m}m-m}l)V+V)l}l*V)V*l}k)V*V*V)k}k*V+V*k}k+V)W*k}k,X*k}j-Y*V)h}g)Y+Z)j}i)W+p}l+W)X)i}l+p}j)W)Z)k}i*W)Z*j}i*^*i}i+]*i}i+W)Z*i}h/Z+h}f)V/[*h}h/[*h}f)V.\\*h}g/\\+g}e)V/\\+g}g/\\+g}e)V/]*g}d)V0]+d)V}V)b)V0]+b*W}W)a)V0]+a*V)V}V)V)`)V0^*`*V)W}V)W)^)V1^+^+V)W}W)V*])V0V)]+[)W*V)X}W)W*\\)V0V)]+\\)V)W)X}W*W*[)V0V)]+Y)V*X)Y}X)X*Y)V1V*]+Y+W*Y}X)X+X)V1V+\\+V)V+W*Z}X*X+W)V1V)V)\\,V+X*Z}Y)Y,V2V)V*[+V+X*[}Y)Z*W2V)W)[*V+Y*[}Y*Z)V3V)W*\\+W)V*\\}Z)Z)V3V)X)[+W)W*\\}Z*Z4V)X*Z*Z*]}Z*Y5V)Y)Z)W)W+]}X)V+X*W0V*Y*X)W)X*^}X*W)W)W*V/V)Y+X*Y+^}X,W)V-V.V)X+^+_}X)W*W/V-V)V,W*V+V,_}X)V)W2V,V,W*V)V,V*`}Y)V)V3V+V*W*X*V,V)`}Y)W5V*V)V*[)V-V)_}Z)V6Y2g}[8b+d}[Hd}[Hd}[Ic}[6[5c}\\4V.W3c}\\3V1V1d}\\2V2W/V*V*V-Y}]1V-V,W.V*V+V,Z}]1V2W-V+V+V)]}^0W0X-V+V+_}^1W.X.V,b}_1^0f}`1[3e}a:Y+e}b7W,h}d4V/g}f8i}i1m}yf}yf}k,p}h)V.V)m}h*V,V*m}yf}j*W*o}j*W*o}yf}yf}~~~";
if(argument0 == 2)
    mydata= "yyr}yyr}yyr}yyr}yyr}_)yv)i}_)yv)i}^+yt+h}^,yr,h}]-yr-g}].yp.g}\\0yn0f}[2\\)y\\)\\2e}[3[)y\\)[3e}Z4Z+yZ+Z4d}Y6Y+yZ+Y6c}X+V,V.X-yX-X.V,V+b}X)Y*W*W*X-yX-X*W*W*Y)b}])Y)[/yV/[)Y)g}[)a0yV0a)e}Z*X*X)W2x2W)X*X*d}Z*W,V*Y-V+v+V-Y*V,W*d}Z3Z+y\\+Z3d}Y5Z)m)i)Z5c}Y5W)Z)e)Y*e)Z)W5c}X6W*X+c*Y)V)c+X*W6b}X6V,V-a)V)Y)W)a-V,V6b}X5W3_)W)Y)X)_3W5b}X4W4^)X)Y)Y)^4W4b}X1V)X5\\)Y)Y)Y)]5X)V1b}X)W+V*V)W6\\)Y)Y)Z)\\6W)V*V+W)b}[)V)W)V)X3V)[)Z)Y)Z)\\)V3X)V)W)V)e}])Y)Y)V*V,^)Z)Y)Z)_,V*V)Y)Y)g}])Y)[)W)V*^)Z)Y)Z)_*V)W)[)Y)g}])Y)[)Y)_)Z)Y)Z)`)Y)[)Y)g}])Y/Z)`)Y)Y)Y)a)Z/Y)g}])e)a)X)Y)X)b)e)g}])e)b)X)W)X)c)e)g}])e)yX)e)g}])e)c.W+c)e)g}\\)Z/Z)`9`)Z/Z)f}[)Z)[)Z)^=^)Z)[)Z)e}[)Y)\\)Z)_;_)Z)\\)Y)e}[)Y)\\)Z3V9V3Z)\\)Y)e}[)Y)\\)e;e)\\)Y)e}[)Y)\\)c)W9W)c)\\)Y)e}[)Y)])a)X9X)a)])Y)e}[)Y)^)c9V)c)^)Y)e}[)Z)^2V+V9V+V2^)Z)e}\\)Z*d+X;X+d*Z)f}\\)\\)cGc)\\)f}])\\)bGb)\\)g}^*Z)b-Y5Y-b)Z*h}`-c1V3V1c-j}s+Z*V1V*Z+yY}s+V+W*V*X*V*W+V+yY}t*V*V)W)V/V)W)V*V*yZ}t+V)V*V)V*X*V)V*V)V+yZ}t+W+V)V/V)V+W+yZ}u+W*V)V)Z)V)V*W+y[}u,X*V/V*X,y[}v.W1W.y\\}w1W)W1y]}y/Z/y_}yV.Z.Y)y[}yV/X/X+yZ}yW.X.X-a7b}yW-W)W,X/\\6W._}yW-V)V)V,Y/Y8W*W+^}yX,W)W,Z?W,Y+]}yX,V+V,[=Y,W-\\}yY+W)W+]<Y3\\}yY+V+V+]=W+W/\\}yY*X)X*]BW/\\}yZ)W,V)^K\\}yZ)X)X)^K\\}yZ)V,W)^K\\}yZ)X)X)^J]}y\\*V*aI]}ymI]}ymI]}ynH]}yoG]}yqD^}yn)YB^}yn)Z7W0^}yn)Z.\\)X0^}yo)Y.[)Z0]}yo)X.\\)Z0]}yo)X.\\)[0\\}yp)W-])\\/\\}yp)V.^)Z)V/[}yr-`)Y)W/Z}yr,X)^)Y)W/Y}yq,Z)^)X)X/X}yq,Z)^)X)Z-X}yq+W)Y)])W)],W}yp+Y)X)])W)^+W}yp*Z)X)\\)W)`*W}yo*[)W)])W)`*W}yn*[)W)])W)b)W}ym*\\)V)^)V)c)W}yl)^*_*d)W}yyr}~~~";
if(argument0 == 1)
    mydata= "yyq}yyq}yyq}yyq}yyq}yyq}yyq}yy[)j}yy[)j}yy[)j}ya)[)j+i}ya*Y*j+i}y`,W,h-h}y`2h-h}y_4g-h}y_*W+W+f/g}y_4f/g}y^-W.e)W*W*f}y^,V)V)V,e1f}y].V)V-e+W,f}y\\8c+V)V)V*f}k/b9^+W,V)V,e}i3^>Y-W3e}g6[BX+W4e}f8ZCX*W5d}e9ZCX*W*W-W*d}d;YCX*W*X+X*d}c<ZAY*W)Y+Y)d}c,V7ZAY*W)Y+Y)d}b>Z?Z*W)Y+Y)d}b>[=[*\\+[)b}b>\\;\\+W)X+W)W*b}a?^8\\-V)X+W)V+b}a<V*`4^/X)V)W-b}a?b0`/X)V)W.a}a?W)r/X)V)W.a}a?W*n)V0X)V)W.a}a;V*W,l*V/Y)V)W.a}a>W-j,V.Y)V)Y+b}a>V0g-W+[)V)Z*b}b8V+W2c0V*\\)V)[)b}b<W6\\3_)V)i}c4V-W9V7X*Z)V)X)e}d9W9V7W*[)V)Y)d}`*Y6W:V8V)\\)V)X)e}_,h:V8X*Y)V)X*d}_.f:V8W+Y)V)X+c}_<X:V8V+Z)V)Z)c}^>W)V8V6V)V*[)V)[)b}^>W)Y5V5W)V)W*X)V)X*d}^>W)^0V1[)X+X)V)X+c}^*c.X)c*V*a)X,X)V)X,b}`6X+X)d)V)b)X+Y)V)Y,a}^;W)Y)b)W)a)X,Y)V)Z+a}]=\\)a)W)`)Y+c+`}]>\\)_)Y)^)Z*Y1X*`}]>],Z)[)[*[*X4W*_}]>a-].b5V*_}]/`+y^2W)W)_}],k)t)X+V2W)W)_}]*m+Z1V2X*W,W5V)_}])n-\\-V.[+W,Y3a}d6Z.k-W,[)Z*b}a9[.Z*[+Y-X+W7`}_:].X-X-W.X*W8`}^1]*_,W/V.W-Y*V9`}^-Y0c*W/V.W,Z*V5W*`}_)X5c)X.V-X*])V5W*`}`8Z+x)W7a}`7Z,X*t)[2a}`-c,X-i+[*W-i}a)c)W*Z*X-`/]5c}k,V*V)Z*]7W*]1W*c}c4V*[*c-\\+]0W)d}c+W*W+V)[.`+_*_0e}b)V3\\+Y.Z+`*v}b*V*V)V)V*X+V*a>^)V)i}b*V+X*X-V)d.^-])V)i}c)W.W0V+`/Z2\\)V)i}l2Y+\\>])V)i}g7\\C_)V)i}c8W*d/j)V)i}b9W*y\\)V)i}b:V*X,h-a)V)i}b;V)W1b0`)V)i}b6W+Y3^2`)V)i}b0W,W+Y4\\3`)V)i}c/W1Y4[3a)V)i}c*W/V-[2]2a)V)i}d)W*V,V-\\0_0b)V)i}d-V-V+_,c,d)V)i}e-V,h*\\*j)V)i}f,V+g,\\,h)V)i}g*k*b*g)V)i}yyZ)V)i}y^*\\*j)V)i}yV2\\1c)V)i}y2]2b)V)i}yyZ+i}yyq}yyq}~~~";
if(argument0 == 0)
    mydata= "yj}h2\\)V)g}f*_/V)V)f}d*]*_)W)e}]/^+c)d}])c,c)d}^*a,c)d}`)_,c)e}`)_,V+^)f}a)]7V*g}],]6V)j}\\)a3V*V*i}]+^0Y*l}])_0V)V)V*V)V)V.a}\\*_0Z+X+V*V)`}\\)`>V-_}[)aD_}[)aD_}[)a5Y3_}[)b4V+V1`}Z)W*_9i}Y)W)W)^1W5b}Y+Y.X3o}_0W)V:f}^2W)V;d}]4V+V;b}]L)a}\\L+`}\\3V:X)X*`}[4W
V)`}[2WCa}[1VG_}[1V0V?^}[0V2V?]}Z,X*V1X>]}Z/X0V0V8]}Z0V0V1W7]}Z0V0V3V6]}[0Y+V5V5]}[4V*V5W3^}\\1W)W5W)V2^}],V-Y)V1V,X._}^+V-W)W)V/W/V,`}b,X,V+[5_}d)X-V*V;_}h-X<_}b)[C_}b,YA`}b-Z?`}b-V)Y=a}b-V*Z:b}a*V*W,[5d}a+X.\\1f}a-W/f0[}a,W)W/a+]*Y}`*V*V2\\)W+b)X}`+X2[)V*Y0Z)W}_-W1\\*Y4Y)V}^*V*W)X-\\)Y6Y)V}^+X1\\)Y8Y)}^,W0\\)Z8Y)}\\+V*V)X,\\)Z9Y)}[-X0\\)Z9Y)}Z,V*W/\\)[9Y)}Y.V)V)X+])\\+Z0Y)}X-V*W/\\)g-Z)}W/X)W,\\)i,Z)}W1V.r+Z)V}V*V0W,r+Z)V}V)W5k,Y*[)V})X4d*Y*Y)X)[)W})Y2e*W*[)W*Z)X})Z0i)])W)Z)Y})\\+e*Y)])W)Y*Z})o*X)])\\)\\})s)])\\)]}V)j*Z)])\\)^}V)j*Y)\\*\\)_}W)]*Z*])Z+\\*`}X)\\*Z*\\/^)b}Y*h,`+c}[*d+a*f}]+_+b)h}`3b*i}e*d*k}c*e)m}b)Z.[)n}a)Z/Z)o}`)Y+W+Z)p}_)Y+W+Z)q}^)Y0Z)r}])Y/[)s}])Y,])t}])d)u}\\)c*v}\\)`+x}\\)Z.yW}\\)V,y]}])ya}yj}yj}~~~";
